BranchMetrics/ios-branch-deep-linking-attribution

Branch-SDK/Branch-SDK/BNCConfig.h
Branch-SDK/Branch-SDK/BNCPreferenceHelper.h
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch.podspec

provide alternative (old) way to specify app key

---

Branch-SDK/Branch-SDK/BNCConfig.h
Branch-SDK/Branch-SDK/BNCServerInterface.m
Branch-SDK/Branch-SDK/BNCSystemObserver.m
Branch-SDK/Branch-SDK/Branch.m
Branch.podspec
ChangeLog.md
README.md

Made CoreTelephony framework optional

---

Branch-SDK/Branch-SDK/BNCServerInterface.m

Fix NSMutableURLRequest setURL issue

---

Branch-SDK/Branch-SDK/BNCConfig.h
Branch.podspec

Added BranchActivityItemProvider.h to podspec

---

Branch-SDK/Branch-SDK/BNCConfig.h
Branch-SDK/Branch-SDK/BNCServerInterface.h
Branch-SDK/Branch-SDK/BNCServerInterface.m
Branch-SDK/Branch-SDK/BNCServerRequestQueue.m
Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchServerInterface.h
Branch-SDK/Branch-SDK/BranchServerInterface.m
Branch.podspec
ChangeLog.md

@aaustin 
Also, 1) excluded close from persist queue, 2) stop operation if ![self hasUser]

Added getShorURLSynchronous

---

Branch-SDK/Branch-SDK/BNCConfig.h
Branch-SDK/Branch-SDK/BNCServerInterface.m
Branch-SDK/Branch-SDK/Branch.m
Branch.podspec
ChangeLog.md

Make sync calls inside interface

---

Branch-SDK/Branch-SDK/BNCConfig.h
Branch-SDK/Branch-SDK/Branch.m
Branch.podspec
ChangeLog.md

Double check delegate in main queue

---

Branch-SDK/Branch-SDK/BNCConfig.h
Branch-SDK/Branch-SDK/BranchServerInterface.m
Branch.podspec
ChangeLog.md

added app_id param to get requests

---

Branch-SDK/Branch-SDK/BranchActivityItemProvider.m

Check iOS version

---

Branch-SDK/Branch-SDK/BNCConfig.h
Branch-SDK/Branch-SDK/Branch.m
Branch.podspec
ChangeLog.md

Callback immediately if initFailed

---

Branch-SDK/Branch-SDK/BNCEncodingUtils.m
Branch-TestBed/Branch-SDK Functionality Tests/BNCEncodingUtilsTests.m

Fixing a bug with encoding of empty dictionaries and arrays.

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/BNCServerInterface.m
Branch-SDK/Branch-SDK/Branch.m

Nil URL Crash

---

Branch-SDK/Branch-SDK/BNCError.m

Shouldn't be passing in an array of strings to the NSError

---

Branch-SDK/Branch-SDK/BNCServerRequest.h
Branch-SDK/Branch-SDK/BNCServerRequest.m
Branch-SDK/Branch-SDK/Branch.m

The issue is not that the session id is nil, but that we're calling setValue:forKey: on an immutable dictionary. This is addressed on a separate branch, but I'm pulling the fix here as well.
@qinweigong @aaustin

Calling setValue:forKey: on an immutable dictionary

---

Branch-SDK/Branch-SDK/BNCEncodingUtils.m
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m

Debugger issues

---

Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed/Branch-TestBed/ReferralCodeViewController.m

@derrickstaten @qinweigong @aaustin @Sarkar 
Also prefixing all enums with Branch. This will be temporarily backwards compatible.

Updating Branch to use NS_ENUMs to represent enum constants.

---

Branch-SDK/Branch-SDK/BNCSystemObserver.m
Branch-TestBed/Branch-SDK Functionality Tests/BNCSystemObserverTests.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj

**Untested / do not merge!**
@shortstuffsushi it should look something like this, if I've done the comparison operation correctly
We can do this in the future, no need to implement today or even this month
Do not thumb up. I just wanted you to see this.

switched to time interval

---

Branch-SDK/Branch-SDK/BranchActivityItemProvider.h
Branch-SDK/Branch-SDK/BranchActivityItemProvider.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.xcworkspace/xcshareddata/Branch-TestBed.xccheckout

@shortstuffsushi this is needed for the new Facebook app. without this Facebook is no longer an option in share sheets

placeholder is now an nsurl

---

Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed/Branch-SDK Functionality Tests/Branch_SDK_Functionality_Tests.m
Branch-TestBed/Branch-SDK Functionality Tests/Branch_SDK_Stubless_Tests.m

Adding the ability to opt out of the app list check. Really quick, simple change.

App list opt out

---

Branch-SDK/Branch-SDK/BNCEncodingUtils.m
Branch-TestBed/Branch-SDK Functionality Tests/BNCEncodingUtilsTests.m

@derrickstaten @Sarkar @jeremiah-de

Iheartradio encoding fix

---

Branch-SDK/Branch-SDK/BNCServerInterface.h
Branch-SDK/Branch-SDK/BNCServerInterface.m
Branch-SDK/Branch-SDK/BNCServerResponse.h
Branch-SDK/Branch-SDK/BNCServerResponse.m
Branch-SDK/Branch-SDK/BranchServerInterface.m
Branch-TestBed/Branch-SDK Functionality Tests/BNCServerInterfaceTests.m

@aaustin @derrickstaten @Sarkar @qinweigong
Title pretty much says it all. Tag isn't needed anymore, removing from server interface and response.

Remove tag from server interface

---

Branch-SDK/Branch-SDK/BNCServerInterface.m

Use a run loop instead of sleeping on the main thread.

Use Run Loops

---

Branch-SDK/Branch-SDK/BNCEncodingUtils.m
Branch-SDK/Branch-SDK/BNCPreferenceHelper.h
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchServerInterface.m
Branch-TestBed/Branch-SDK Functionality Tests/BNCPreferenceHelperTests.m
Branch-TestBed/Branch-SDK Functionality Tests/Branch_SDK_Functionality_Tests.m

The server doesn't want this, and internally we're basically just using it as a nil check.

Remove all instances of NO_STRING_VALUE.

---

Branch-SDK/Branch-SDK/BNCError.h
Branch-SDK/Branch-SDK/BNCServerInterface.m
Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed/Branch-SDK Functionality Tests/BranchNetworkScenarioTests.m

Separating out failure codes for a bad user request and a Branch server problem.
Fixing check to continue processing in Branch.

Error Code Update

---

Branch-SDK/Branch-SDK/BNCEncodingUtils.m

@aaustin 
Something in the base64 encoding was causing problems when creating the activity item provider. This just changes that impl and now it works.

Share Sheet Fix

---

Branch-SDK/Branch-SDK/BNCSystemObserver.h
Branch-SDK/Branch-SDK/BNCSystemObserver.m
Branch-SDK/Branch-SDK/BranchInstallRequest.m
Branch-SDK/Branch-SDK/BranchOpenRequest.m

@MaxwellLevenson @qinweigong 
Adding another item to the open and install requests.

Adding bundle identifier to open / install requests.

---

Branch-SDK/Branch-SDK/BNCLinkCache.h
Branch-SDK/Branch-SDK/BNCLinkCache.m
Branch-SDK/Branch-SDK/BNCLinkData.h
Branch-SDK/Branch-SDK/BNCLinkData.m
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchShortUrlRequest.m
Branch-SDK/Branch-SDK/BranchShortUrlSyncRequest.m
Branch-TestBed/Branch-SDK Functionality Tests/BNCLinkDataTests.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj

@qinweigong 
Cleaning up LinkData, and removing `toLowercase`.

Link data clean up

---

Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchCloseRequest.m

Fix a potential crash scenario when session is nil.

---

Branch-SDK/Branch-SDK/BNCServerRequestQueue.m

Removing a whole bunch of false-safety nets.

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.h
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/Branch.m

Fix update state check

---

Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchLogoutRequest.h
Branch-SDK/Branch-SDK/BranchLogoutRequest.m
Branch-TestBed/Branch-SDK Functionality Tests/Branch_SDK_Functionality_Tests.m

On successful logout, the link cache should be cleared.

---

Branch-SDK/Branch-SDK/BNCLinkData.h
Branch-SDK/Branch-SDK/BNCLinkData.m
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchCloseRequest.m

Safety nets

---

Branch-SDK/Branch-SDK/BranchGetAppListRequest.h
Branch-SDK/Branch-SDK/BranchGetAppListRequest.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj

@qinweigong Sorry but can you help me merge this one too? I should have
read his code more closely..

Urgent: just notified that get applist is persisted too

---

Branch-SDK/Branch-SDK/BNCEncodingUtils.m

Use `strlen()` instead of `length` of `NSString`

Encoded data length issues

---

Branch-SDK/Branch-SDK/Branch.m

There has been too much confusion around setting isReferrable only on
fresh installs.
@shortstuffsushi

Change isReferrable default

---

Branch-SDK/Branch-SDK/Core/BNCStrongMatchHelper.h
Branch-SDK/Branch-SDK/Core/BNCStrongMatchHelper.m
Branch-SDK/Branch-SDK/Core/Branch.m

@aaustin @shortstuffsushi note this is a PR to add to ios-9-content-discovery, not to master. pings 1x every 30 days to avoid too much server load but also to keep up with rotating IDFA's or cleared browser cookies

Perfect matching

---

Branch-SDK/Branch-SDK/BNCSystemObserver.m
Branch-TestBed/Branch-SDK-Tests/BNCSystemObserverTests.m

@derrickstaten 
Fix scenario where uri scheme is < 3 characters length causing crash.
Add test around this scenario.

Short URI Scheme Fix

---

Branch-SDK/Branch-SDK/BNCServerInterface.m

handle 400 errors

---

Branch-SDK/Branch-SDK/BNCEncodingUtils.m
Branch-SDK/Branch-SDK/BNCServerInterface.m
Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.h
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj

@aaustin @Sarkar this is my initial pass. I haven't tested this extensively. I'm going to do so now. Please look for any potential issues.

stop using deprecated methods

---

Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
Branch.podspec

@Sarkar @aaustin pending tests passing, let's release 0.11.1

podspec change: allow deploying against ios6+

---

Branch-SDK/Branch-SDK/Branch.m

@aaustin @Sarkar this fixes spotlight search / UL not working on cold start
However, I'm not sure if there are other side effects to doing this, like failing to initialize in certain scenarios. I want to test, and if you have scenarios you think I should test please let me know

fix universal links not returning deeplink data on cold start

---

Branch-SDK/Branch-SDK/Branch.m

Ios 7 compatibility

---

Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.h
Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m
README.md

make new initsession check safe for version prior to ios 8

---

Branch-SDK/Branch-SDK/BNCContentDiscoveryManager.m
Branch-SDK/Branch-SDK/BNCPreferenceHelper.h
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m
Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
Branch.podspec

iOS9 updates

---

Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m

option to disable cookie-based matching

---

Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchActivityItemProvider.m
Branch-SDK/Branch-SDK/Requests/BranchShortUrlSyncRequest.h
Branch-SDK/Branch-SDK/Requests/BranchShortUrlSyncRequest.m

@aaustin @Sarkar sorry for the nasty diff, I had to update a bunch of methods in order to pass one new param through

fallback to /a/ link for BranchActivityItemProvider

---

Branch-SDK/Branch-SDK/Branch.m

dismiss modal before presenting another modal

---

Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m

@aaustin leave on branch until 0.11.5 release

better view controller presentation/dismissal to not trigger warnings

---

Branch-SDK/Branch-SDK/BNCServerInterface.m

invalidate NSURLSession to avoid memory leaks

---

Branch-SDK/Branch-SDK/Branch.m

add checks throughout

---

README.md

Add notice for deprecation

---

Branch-SDK/Branch-SDK/Branch.h

feedback on deprecation warning text. 
@derrickstaten @aaustin

Add deprecation warnings to loadActionCounts

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m

safer unarchiving

---

Branch-SDK/Branch-SDK/BNCSystemObserver.m

set debug still allows real hardware id

---

Branch-SDK/Branch-SDK/Requests/BranchConnectDebugRequest.m
Branch-SDK/Branch-SDK/Requests/BranchDisconnectDebugRequest.m
Branch-SDK/Branch-SDK/Requests/BranchLogRequest.m

add session_id and identity_id to debug

---

Branch-SDK/Branch-SDK/Branch.h

not confusing comments

---

README.md

added universal object to docs - removed getShortUrl

Universal Object Boom

---

Branch-SDK/Branch-SDK/Branch.m

Checking for initSession being in progress seems to eliminate the race condition on startup.

Race condition fixed!  I hope! :)

---

Branch-SDK/Branch-SDK/BranchUniversalObject.m
Branch-TestBed/Branch-TestBed/UniversalObjectViewController.m

fix for UIActivityViewController presentation on iPads

---

Branch-SDK/Branch-SDK/Branch.m

revert initSession race condition check

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/Requests/BranchOpenRequest.m

Queue for prefs helper

---

Branch-SDK/Branch-SDK/Requests/BranchSetIdentityRequest.m

make sure that we don't set a nil value for session id

---

Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/Requests/BranchSetIdentityRequest.m

@danwalkowski @aaustin note that this purposefully includes one other commit (submitted in a different PR) so that I can ask a partner to test this.

Readd initsession check

---

Branch-SDK/Branch-SDK/BNCSystemObserver.m

allow dashboard debug mode on iOS 9

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.h
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/Branch.m

@aaustin @danwalkowski 
in plist, users should enter `branch_universal_link_domains` and put either a string or an array of strings.

allow users to specify branch_universal_link_domains

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-TestBed/Branch-SDK-Tests/BNCPreferenceHelperTests.m

- changed network timeout from 5 seconds to 5.5 seconds
- changed retry count from 1 to 3

Client timeout changes

---

Branch-SDK/Branch-SDK/Branch.m

@danwalkowski @aaustin we'll need to test this extensively. I can demonstrate the race condition in person, using a VPN through HK to simulate slow Internet. This is a rare condition that will almost never occur.

after initsession, close the app if now in bg

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m

@aaustin @danwalkowski I'm not sure why, but this typo is causing a crash on all my simulators

fix setUserUrl capitalization

---

Branch-TestBed/Branch-SDK-Tests/BranchConnectDebugRequestTests.m
Branch-TestBed/Branch-SDK-Tests/BranchDisconnectDebugRequestTests.m

fix debug tests

---

Branch-SDK/Branch-SDK/Requests/BranchRegisterViewRequest.m

@dmitrig01 @danwalkowski @aaustin -- new request format:
```
{
"ad_tracking_enabled" = 1;
"app_version" = "1.2";
"branch_key" = "key_live_jbgnjxvlhSb6PGH23BhO4hiflcp3y8kx";
data =     {
"$canonical_identifier" = id12345;
"$exp_date" = 0;
"$og_description" = "My awesome piece of content!";
"$og_image_url" = "https://s3-us-west-1.amazonaws.com/branchhost/mosaic_og.png";
"$og_title" = "";
"$publicly_indexable" = 1;
foo = bar;
};
debug = 1;
"device_fingerprint_id" = 201052188485690205;
"device_name" = "iPhone Simulator Derricks-MacBook-Pro.local";
"identity_id" = 201052188510789641;
"is_simulator" = 1;
model = "x86_64";
os = iOS;
"os_version" = "9.1";
retryNumber = 0;
sdk = "ios0.11.11";
"session_id" = 201052905229263252;
}
```

update register-view call so it's no longer a flat object

---

Branch-SDK/Branch-SDK/BNCStrongMatchHelper.h
Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m
Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/Requests/BranchInstallRequest.m

@danwalkowski @aaustin @Sarkar 100% matching is back

100 matching prototype

---

Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m

Same as previous pull request but a couple things different.

Broken UIViewControllerBasedStatusBarAppearance and unbalance view transition calls

---

Branch-SDK/Branch-SDK/Branch.m

fix race condition with check

---

Branch-SDK/Branch-SDK/Requests/BranchSpotlightUrlRequest.m

include channel when generating spotlight link

---

Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
Branch-TestBed/Branch-TestBed/AppDelegate.m

@derrickstaten
still needs a bit of logic

iOS deferred deep linking apns

---

Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m

Generic request handler

---

Branch-SDK/Branch-SDK/BranchUniversalObject.m

Fixed an issue where share text was being inserted after share URL.

Moved share text before URL.

---

Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m

@aaustin support slower connection speeds.

increase timeout for SFSafariViewController

---

Branch-SDK/Branch-SDK/BranchUniversalObject.h
Branch-SDK/Branch-SDK/BranchUniversalObject.m

Expose function

---

Branch-SDK/Branch-SDK/Requests/BranchShortUrlRequest.m
Branch-SDK/Branch-SDK/Requests/BranchShortUrlSyncRequest.m

append the right match URL parameter sent to the API

fix match parameter sent to API

---

Branch-SDK/Branch-SDK/BranchUniversalObject.h
Branch-SDK/Branch-SDK/BranchUniversalObject.m

@aaustin @derrickstaten @Sarkar

account for different anchors for share sheet on iPad

---

Branch-SDK/Branch-SDK/BranchUniversalObject.m

@derrickstaten @aaustin @Sarkar

add canonical url and ID to spotlight indexing

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/Requests/BranchOpenRequest.m
Branch-TestBed/Branch-TestBed/AppDelegate.m
Branch-TestBed/Branch-TestBed/ViewController.m

@ahmednawar Hot fix for all affected

Will prevent future crashes

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m

typecast installParams

---

Branch-SDK/Branch-SDK/BranchView.m
Branch-SDK/Branch-SDK/Requests/BranchOpenRequest.m
Branch-SDK/Branch-SDK/Requests/BranchUserCompletedActionRequest.m

Back-end is sending the BranchViewData as  a dictionary rather than Json String. Adding support for dictionary  for Branch view data
@derrickstaten @aaustin @ahmednawar

Adding support for Branch View  Data as dictionary

---

PULL_REQUEST_TEMPLATE.md

Create Pull Request Template

---

Branch-SDK/Branch-SDK/BNCServerInterface.m

Background: Our current code rely on compile-time macros to check for the availability with NSURLSession which was introduced in iOS 7. We can't rely on compile-time checks because the binary ships with one code path(NSURLSession) which fails on iOS 6. 
PR: changes the logic to rely on run-time checks. The code might be a bit confusing because it defines the completionhandler blocks before the request functions. I added some inline comments but not sure whether it is clear.
Tested on iOS 6, 7, 8, and 9
@aaustin @derrickstaten @Sarkar

check for nsurlsession availability

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.h
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/BNCServerRequestQueue.m
Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m
Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchUniversalObject.m

Thumbed here #322..opened her to merge with `staging` instead of `master`

suppress warning logs [staging]

---

circle.yml

hopefully this fixes the build failure

update simulator os version

---

Branch-SDK/Branch-SDK/BranchViewHandler.h
Branch-SDK/Branch-SDK/BranchViewHandler.m
Branch-TestBed/Branch-TestBed/ViewController.m

- Now only show the web view after a successful load of the page
- Do not show the web view if any http status code other than 200 is
received

BranchViewHandler Changes

---

Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/Requests/BranchShortUrlSyncRequest.m

@dmitrig01 @derrickstaten @aaustin 
cc @scott-branchio

Subd support 1

---

Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m

window ptr

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.h
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/BNCServerInterface.m
Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m

add metadata to every request

---

Branch-SDK/Branch-SDK/BNCDeviceInfo.m
Branch-SDK/Branch-SDK/BNCSystemObserver.h
Branch-SDK/Branch-SDK/BNCSystemObserver.m

add vendor id all the time

---

Branch-SDK/Branch-SDK/Branch.m

https://github.com/BranchMetrics/ios-branch-deep-linking/issues/332

Fixes issue #332 by explicitly specifying path to header files

---

Branch-TestBed/module.modulemap
Branch.framework/Modules/module.modulemap
carthage-files/module.modulemap

Updates modulemaps to describe framework dependencies

---

scripts/release.sh

automatically update fabric kit display version upon release similar to what we do with `BNCConfig` and the `podspec`

automatically update fabric kit display version upon release

---

Branch-SDK/Branch-SDK/BNCSystemObserver.m

Handle all zeros-IDFA on iOS 10 when ad tracking is limited

Idfa ios10

---

Branch-TestBed/Branch-TestBed/ViewController.m

putting back the old share sheet code in the the TestBed's ViewController. I changed earlier for some testing and forgot to revert.

uncomment old share sheet code in testbed

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.h
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/BNCServerInterface.m
Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m
Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed/Branch-SDK-Tests/BNCServerInterfaceTests.m

Bid app key farewell

---

Branch-SDK/Branch-SDK/Branch.m

@Zhukn1 @ahmednawar This should fix things

Don't return nil params on error

---

carthage-files/BranchSDK.xcodeproj/project.pbxproj
carthage-files/Info.plist

delete deprecated files

---

README.md
carthage-files/BranchSDK.xcodeproj/project.pbxproj

This is the actual fix for #392

Fix path to module.modulemap

---

Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed/Branch-TestBed/AppDelegate.m

@derrickstaten @ahmednawar @sojanpr Urgent functionality exposure for premium partner.
This method allows the developer to white list URI schemes that Branch can track, in case there are private URI schemes that carry sensitive information.

White listed schemes

---

Branch-TestBed/Branch-TestBed/AppDelegate.m
Branch-TestBed/Branch-TestBed/Branch-TestBed-Info.plist

@dwestgate tiny changes to testbed

minor stuff

---

Branch-SDK/Branch-SDK/BNCServerInterface.m

move to the scope to local to prevent collision with similar variable names
@aaustin

change variable scope

---

Branch-SDK/Branch-SDK/Branch.m

remove debug gesture

---

scripts/checksum.sh
scripts/upload_zips.sh

having some integrity
@aaustin cc @abelfletcher @sojanpr

add checksumming to the release procedure

---

Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m

Minor optimization

---

Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchUniversalObject.h
Branch-SDK/Branch-SDK/BranchUniversalObject.m
Branch-SDK/Branch-SDK/Requests/BranchShortUrlRequest.h
Branch-SDK/Branch-SDK/Requests/BranchShortUrlRequest.m
Branch-SDK/Branch-SDK/Requests/BranchSpotlightUrlRequest.m
Branch-TestBed/Branch-TestBed/ViewController.m

First set of BUO changes. This covers the following changes from the spec: 0, 2, 3, 4, 5.
@aaustin @zeeshabnc

Make BUO great!

---

Branch-SDK/Branch-SDK/BNCContentDiscoveryManager.h
Branch-SDK/Branch-SDK/BNCContentDiscoveryManager.m
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchUniversalObject.h
Branch-SDK/Branch-SDK/BranchUniversalObject.m
Branch-TestBed/Branch-TestBed/AppDelegate.m
Branch-TestBed/Branch-TestBed/ViewController.m

Spotlight indexing for BUO + auto share events. 
https://branch.atlassian.net/browse/AIS-47
@aaustin cc @zeeshabnc @sdkdeepa

AIS-47 - Spotlight

---

Branch-SDK/Branch-SDK/BNCContentDiscoveryManager.m
Branch-SDK/Branch-SDK/BNCServerInterface.m
Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchUniversalObject.m
Branch-SDK/Branch-SDK/BranchViewHandler.m

Will add "1" with the key `ios_extension` if the SDK is being used in an extension. Key won't be present if not.

Tracking iOS extension usage

---

Branch-SDK/Branch-SDK/BNCContentDiscoveryManager.m
Branch-SDK/Branch-SDK/BranchUniversalObject.h

AIS-60: add nullability type annotations to BUO

---

Branch-SDK/Branch-SDK/BNCServerInterface.m

replace containsString with rangeOfString for iOS 7 support
@derrickstaten @aaustin

AIS-76: iOS 7 fix

---

iOS_SDK_Release_Procedure

Updated iOS SDK release procedure. Let me know if anything needs further clarification.
@aaustin @sojanpr @zeeshabnc

updated release procedure

---

Branch-SDK/Branch-SDK/BNCStrongMatchHelper.h
Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m
Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed/Branch-TestBed/AppDelegate.m

New onboarding option

---

Branch-TestBed/README.md
README.md

Added Objective-C TestBed readme.md

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.h
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchConstants.h
Branch-SDK/Branch-SDK/BranchConstants.m
Branch-SDK/Branch-SDK/BranchContentDiscoverer.h
Branch-SDK/Branch-SDK/BranchContentDiscoverer.m
Branch-SDK/Branch-SDK/BranchContentDiscoveryManifest.h
Branch-SDK/Branch-SDK/BranchContentDiscoveryManifest.m
Branch-SDK/Branch-SDK/BranchContentPathProperties.h
Branch-SDK/Branch-SDK/BranchContentPathProperties.m
Branch-SDK/Branch-SDK/Requests/BranchCloseRequest.m
Branch-SDK/Branch-SDK/Requests/BranchOpenRequest.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj

Changing content discovery base to Staging
@aaustin

Adding Content  discovery to current staging

---

Branch-SDK/Branch-SDK/BranchUniversalObject.h

Fix BUO nullables

---

Branch-SDK/Branch-SDK/Branch.m

Protection for  a corner case crash reported by partner. 
@aaustin

Crash Prevention For Request Fail

---

Branch-SDK/Branch-SDK/Branch.m

@aaustin fix for bug where initSession would hang on cold launch if universal link tapped

hotfix for facebook shouldWaitForInit functionality

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.h
Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/Requests/BranchInstallRequest.m

setInstallRequestDelay

---

Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m

launchOptions dictionary contains null values if passed from Swift

---

Branch-SDK/Branch-SDK/BranchActivityItemProvider.m

AIS-84 Note scrape

---

README.md

Updated the code provided for initSession, continue(userActivity) and openURL

Updated Syntax

---

Branch-SDK/Branch-SDK/Branch.h

minor change
@derrickstaten @E-B-Smith

fix disableCookieBasedMatching comment

---

README.md

Updated doc for application:willFinishLaunchingWithOptions:

---

.gitignore

I cleaned up the gitignore file and added a few items.  Let me know if this breaks someones work flow.

Updated .gitignore file.

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.h
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/BNCServerRequestQueue.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj

@aaustin I've touched some work queue stuff in here so please make sure I'm on track.

Fix for INTENG-2882

---

Branch-SDK/Branch-SDK/BNCDeviceInfo.h
Branch-SDK/Branch-SDK/BNCDeviceInfo.m
Branch-SDK/Branch-SDK/BNCServerInterface.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
ChangeLog.md
ReleaseNotes.md

* AIS-106: Included user_agent in device POST parameters.
* AIS-109: Included language & country in device POST parameters.

Add-Keys-AIS-109-AIS-106

---

Branch-SDK/Branch-SDK/BranchActivityItemProvider.m
ChangeLog.md

Update Slack channel name (AIS-59)

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/BNCServerRequestQueue.m

nil checks for file move op

---

Branch-SDK/Branch-SDK/BranchActivityItemProvider.m

Channel name should be consistent across iOS and Android (for top sharing channels)
@E-B-Smith cc @zeeshabnc @EvangelosG

AIS-112 relabel top channels to match Android

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-TestBed/Branch-TestBed/Base.lproj/Main.storyboard
Branch-TestBed/Branch-TestBed/LaunchScreen.storyboard

• Update storyboards to accommodate iOS 7 QA testing.
• Updated release deployment scripts.
• Added try/catch block for safety around unarchiving preferences.

Update QA 

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/BNCServerRequestQueue.h
Branch-SDK/Branch-SDK/BNCServerRequestQueue.m
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/Requests/BranchOpenRequest.h
Branch-SDK/Branch-SDK/Requests/BranchOpenRequest.m
Branch-TestBed/Branch-TestBed/Base.lproj/Main.storyboard
Branch-TestBed/Branch-TestBed/LaunchScreen.storyboard
Branch-TestBed/Branch-TestBed/main.m

This fixes the JIRA issue https://branch.atlassian.net/browse/AIS-128
This fix has been tested on iOS 10/9/8/7 and opens links as expected.
@aaustin you may want to look this PR over since it changes the way the network queue handles requests.

Queued Opens AIS-128

---

Branch-SDK/Branch-SDK/BNCStrongMatchHelper.h
Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m
Branch-TestBed/Branch-TestBed/Base.lproj/Main.storyboard
Branch-TestBed/Branch-TestBed/LaunchScreen.storyboard
Branch-TestBed/Branch-TestBed/main.m

Creating a SFSafariViewController and adding a temporary key window was interfering with partners applications:
* Losing the keyWindow focus stalled UI initialization.
* Controls would lose firstResponder status.
* The Facebook login controller wouldn't appear correctly.
This patch fixes those problems.

Safari key window AIS-122

---

Branch-SDK/Branch-SDK/BNCCommerceEvent.h
Branch-SDK/Branch-SDK/BNCCommerceEvent.m
Branch-SDK/Branch-SDK/BNCConfig.m
Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m
Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed-iMessage/Branch-TestBed-iMessage.xcodeproj/project.pbxproj
Branch-TestBed-iMessage/MessagesExtension/MessagesViewController.h
Branch-TestBed-iMessage/MessagesExtension/MessagesViewController.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
Branch-TestBed/Branch-TestBed/AppDelegate.m
Branch-TestBed/Branch-TestBed/Base.lproj/Main.storyboard
Branch-TestBed/Branch-TestBed/ViewController.m

This patch adds a structured "commerce" event to the Branch SDK.

Commerce DANA-39

---

Branch-SDK/Branch-SDK/BNCConfig.h
Branch-SDK/Branch-SDK/BNCConfig.m
Branch-SDK/Branch-SDK/BNCServerInterface.m
Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m
Branch-SDK/Branch-SDK/Branch.m
Branch.podspec
carthage-files/Info.plist
scripts/version

Changed SDK_VERSION to BNC_SDK_VERSION.

---

Branch-SDK/Branch-SDK/BNCDeviceInfo.m
Branch-SDK/Branch-SDK/Branch.m

* Cached the browserUserAgentString in BNCDeviceInfo.
* Made 'makeRequest' run asynchronously.

Return faster from the Branch initialization call.

---

Branch-SDK/Branch-SDK/BNCLinkData.m
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/Requests/BranchShortUrlRequest.m

Don't add 'type' or 'duration' to link data if they're 0.

---

Branch-SDK/Branch-SDK/BNCSystemObserver.m
Branch-TestBed/Branch-TestBed.xcodeproj/xcshareddata/xcschemes/Branch-TestBed.xcscheme
Branch-TestBed/Branch-TestBed/AppDelegate.m
Branch-TestBed/Branch-TestBed/Base.lproj/Main.storyboard

This patch fixes the iOS 10.2.2 app install/update reporting bug.

---

Branch-TestBed-Swift/Podfile
Branch-TestBed-Swift/TestBed-Swift.xcodeproj/project.pbxproj
Branch-TestBed-Swift/TestBed-Swift/ContentViewController.swift
Branch-TestBed-Swift/TestBed-Swift/CreditHistoryViewController.swift
Branch-TestBed-Swift/TestBed-Swift/Info.plist

- Fixed bug that prevented FirstReferringParams from displaying
- Updated to SDK version v0.12.20

Test bed swift

---

Branch-SDK/Branch-SDK/Branch.m

Revert lifecycle change in 0.12.18

---

Branch-SDK/Branch-SDK/Requests/BranchUserCompletedActionRequest.m

Added a warning when a user event conflicts with a Branch commerce event.

Warn when a user event commerce conflicts DANA-77

---

Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj

Updated project for Fabric.

---

scripts/deploy-beta
scripts/deploy-git-tag

Added deploy-beta.

---

ChangeLog.md

Adding more information to release notes for 0.12.24
cc. @aaustin @E-B-Smith

Adding more information to release notes for 0.12.24

---

Branch-TestBed-Swift/TestBed-Swift.xcodeproj/project.pbxproj
Branch-TestBed-Swift/TestBed-Swift/Base.lproj/LaunchScreen.storyboard
Branch-TestBed-Swift/TestBed-Swift/Base.lproj/Main.storyboard
Branch-TestBed-Swift/TestBed-Swift/ViewController.swift
Branch-TestBed/Branch-TestBed/ViewController.m

Add Commerce Example to TestBed-Swift AIS-177

---

Branch-SDK/Branch-SDK/BNCServerInterface.m

Potentially fixed a crash casued by a prematurely dellocated static variable in BNCServerInterface.m

---

Branch-SDK/Branch-SDK/BranchViewHandler.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
Branch-TestBed/Branch-TestBed.xcodeproj/xcshareddata/xcschemes/Branch-SDK-Tests.xcscheme
Branch-TestBed/Branch-TestBed.xcodeproj/xcshareddata/xcschemes/Branch-TestBed.xcscheme
Branch-TestBed/Branch-TestBed.xcodeproj/xcshareddata/xcschemes/Branch.xcscheme

Update settings and includes for Xcode 8.3.

---

Branch-TestBed-Swift/TestBed-Swift/Base.lproj/LaunchScreen.storyboard
Branch-TestBed-Swift/TestBed-Swift/Base.lproj/Main.storyboard
Branch-TestBed-Swift/TestBed-Swift/ViewController.swift
Branch-TestBed/Branch-TestBed/Base.lproj/Main.storyboard
Branch-TestBed/Branch-TestBed/LaunchScreen.storyboard
Branch-TestBed/Branch-TestBed/ViewController.m

Changed the 'buy' event to a 'button' a event to make it distinct from the new commerce event.

Changed the 'buy' event to a 'button' a event.

---

Branch-SDK/Branch-SDK/BNCDeviceInfo.m
Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m
Branch-SDK/Branch-SDK/Requests/BranchOpenRequest.m

Removed NSLog statements added for debugging.

---

Branch-SDK/Branch-SDK/NSMutableDictionary+Branch.m

Make deep copy of dictionary before adding.

---

Branch-SDK/Branch-SDK/BranchContentDiscoveryManifest.m

Fixed content manifest race condition.

---

Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed/Branch-SDK-Tests/BranchNetworkScenarioTests.m

Perform callbacks on the main thread.

---

Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchContentDiscoverer.h
Branch-SDK/Branch-SDK/BranchContentDiscoverer.m
Branch-SDK/Branch-SDK/Requests/BranchOpenRequest.m
ChangeLog.md

Content discovery -- the revenge

---

Branch-SDK/Branch-SDK/Branch.m

Update final main thread callback.
* Removed the final conditional compilation that I added for unit testing.

Final main thread call back.

---

Branch-SDK/Branch-SDK/BNCFabricAnswers.m

Fixed crash bug when adding Branch identity to Fabric answers.

---

Branch-SDK/Branch-SDK/BNCCommerceEvent.m

Tested with the Testbed app.  The transaction appears in the commerce tab.

Changed transactionID to transaction_id.

---

Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
Branch-TestBed/Branch-TestBed/AppDelegate.m
README.md

Updated readme file and example.

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.h
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/BNCSystemObserver.m
Branch-SDK/Branch-SDK/Requests/BranchLoadRewardsRequest.m
Branch-TestBed/Branch-SDK-Tests/BNCServerInterfaceTests.m
Branch-TestBed/Branch-SDK-Tests/BNCSystemObserverTests.m
Branch-TestBed/Branch-SDK-Tests/BranchLoadRewardsRequestTests.m
Branch-TestBed/Branch-SDK-Tests/BranchNetworkScenarioTests.m
Branch-TestBed/Branch-SDK-Tests/BranchSDKFunctionalityTests.m
Branch-TestBed/Branch-SDK-Tests/BranchSDKLoadTests.m
Branch-TestBed/Branch-TestBed.xcodeproj/xcshareddata/xcschemes/Branch-TestBed.xcscheme
Branch-TestBed/Branch-TestBed/AppDelegate.m
scripts/test-unit-tests

Fixed reward and system observer unit tests.

---

Branch-SDK/Branch-SDK/BranchActivityItemProvider.m
Branch-SDK/Branch-SDK/BranchUniversalObject.m
Branch-SDK/Branch-SDK/Requests/BranchShortUrlSyncRequest.m
Branch-TestBed-Swift/TestBed-Swift.xcodeproj/project.pbxproj

* Use the cached userAgentString when possible.  
* Organize BranchUniversalObject.m code by functionality.  
* Add short link failure warning.

Add short link warnings and tidy up AIS-208

---

Branch-SDK/Branch-SDK/BranchUniversalObject.h
Branch-SDK/Branch-SDK/BranchUniversalObject.m

This follows the Android model: https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/indexing/BranchUniversalObject.java#L289.

Added [BUO userCompletedAction:withState:]

---

Branch-SDK/Branch-SDK/BNCXcode7Support.h
Branch-SDK/Branch-SDK/BranchShareLink.m
Branch-TestBed-Swift/TestBed-Swift/Base.lproj/Main.storyboard
Branch-TestBed-Swift/TestBed-Swift/ViewController.swift
Branch-TestBed-Xcode-7/Branch-TestBed.xcodeproj/project.pbxproj

Added link alias example and added Xcode 7 support.

---

Branch-SDK/Branch-SDK/BNCSystemObserver.h
Branch-SDK/Branch-SDK/BNCSystemObserver.m
Branch-TestBed/Branch-SDK-Tests/BNCSystemObserverTests.m

* enterprise-update-INTENG-3189

Fixed `getUpdateState` so it works on Enterprise apps too.

---

Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed-Swift/TestBed-Swift/AppDelegate.swift
Branch-TestBed/Branch-TestBed/AppDelegate.m

Appboy Open URL Update INTENG-3242

---

Branch-SDK/Branch-SDK/BranchShareLink.m
Branch-TestBed-Swift/TestBed-Swift/Base.lproj/Main.storyboard
Branch-TestBed-Swift/TestBed-Swift/ViewController.swift

Updated the BranchShareLink so the activity item children own the parent.

---

Branch-TestBed-Swift/TestBed-Swift/ViewController.swift
Branch-TestBed/Branch-TestBed/ViewController.m

Added sharing text with date.

---

Branch-SDK/Branch-SDK/BNCConfig.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
Branch.podspec
ChangeLog.md
carthage-files/BranchSDK.xcodeproj/project.pbxproj
carthage-files/BranchSDK.xcodeproj/xcshareddata/xcschemes/Branch iOS SDK Carthage.xcscheme
carthage-files/Info.plist
scripts/version

Added BranchShareLink.h to public headers.

---

Branch-SDK/Branch-SDK/BNCXcode7Support.h
Branch-SDK/Branch-SDK/Branch.h
Branch-TestBed-Xcode-7/Branch-TestBed.xcodeproj/project.pbxproj
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
carthage-files/BranchSDK.xcodeproj/project.pbxproj

Fixed headers for Swift compatability.

---

Branch-SDK/Branch-SDK/BNCLog.h
Branch-SDK/Branch-SDK/BNCLog.m
Examples/WebViewExample/Podfile
Examples/WebViewExample/WebViewExample.xcodeproj/project.pbxproj
Examples/WebViewExample/WebViewExample/AppDelegate.swift
Examples/WebViewExample/WebViewExample/Utilities/BNCLog.swift

* Better naming for logging functions. 
* More intuitive defaults.

Update Logging Names

---

Branch-TestBed/Branch-TestBed/Base.lproj/Main.storyboard
Branch-TestBed/Branch-TestBed/ViewController.m

Shows how to open a Branch link triggered by an in-app event.

---

Branch-SDK/Branch-SDK/BNCCommerceEvent.h
Branch-SDK/Branch-SDK/BNCCommerceEvent.m
ChangeLog.md

This adds parity to the Android implementation.

Add currency type for commerce events - AIS-275

---

Branch-SDK/Branch-SDK/Branch.m

Universal Links and URI scheme is combined into one API:
- (BOOL)handleDeepLink:(NSURL *)url fromSelf:(BOOL)isFromSelf
Hence, it would check the URL whether its universal link or URI scheme and react accordingly.

Branch support for AppBoy - AIS-264

---

README.md

Added code snippets to show how BranchSharelinkDelegate is inherited and allows Branch link customization on the fly.

branchSharelinkDelegate doc update

---

Examples/WebViewExample/WebViewExample/ArticleViewController.swift

* Fixed the compile warning by switching the the BranchShareLink interface.

Fixed the compile warning in the WebViewExample.

---

Branch-SDK/Branch-SDK/BNCDeviceInfo.m
Branch-TestBed-Xcode-7/Branch-TestBed.xcodeproj/project.pbxproj

* Made a fix for device country code crash.
* Enabled on on-device unit testing for iOS 7.

This should fix the strange GitHub #644 crash.

---

Branch-SDK/Branch-SDK/BNCFabricAnswers.h
Branch-SDK/Branch-SDK/BNCFabricAnswers.m
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m
Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
Branch-TestBed/Branch-TestBed/AppDelegate.m
Branch.podspec

* Siloed off Fabric calls.
* Removed CoreTelephony.
* Made SafariServices an optional podspec.

Optional Frameworks (AIS-290)

---

Branch-SDK/Branch-SDK/BNCDeviceInfo.m

Decoupled country code discovery from language discovery.

---

Branch-SDK/Branch-SDK/BranchUniversalObject.h

Removed deprecation notices.

---

Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchShortUrlRequest.m

By default, Dynamic links are created every time internet connectivity is down.
- Set forceLinkCreation to YES by default.
- Fixed indentation.

INTENG-3579 Default dynamic links fix

---

Branch-SDK/Branch-SDK/BNCLocalization.m

Stab #2 at the Russian translation.

---

Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
Branch-TestBed/Branch-TestBed.xcodeproj/xcshareddata/xcschemes/Branch-TestBed.xcscheme
Branch-TestBed/Branch-TestBed/Base.lproj/Main.storyboard
Branch-TestBed/Branch-TestBedUITests/Branch_TestBedUITests.m
Branch-TestBed/Branch-TestBedUITests/Info.plist

Automated UITest Implemented on TestBed Obj-C app to test Universal Links. This can be used to validate Universal Link's behavior on any version of iOS or Apple device.

UITest Automation for Universal Links on TestBed - Obj-C [AIS-187]

---

Branch-SDK/Branch-SDK/BNCSystemObserver.m

Added 'com.googleusercontent.apps' as an oauth scheme.

---

Branch-SDK/Branch-SDK/BNCLog.m
Branch-TestBed/Branch-TestBed.xcodeproj/xcshareddata/xcschemes/Branch-SDK-Tests.xcscheme
Branch-TestBed/Branch-TestBed.xcodeproj/xcshareddata/xcschemes/Branch-TestBed.xcscheme

Checked offset before reading pointer.

---

Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m

Added runtime OS version check to BNCStrongMatchHelper

---

Branch-SDK/Branch-SDK/BranchShareLink.m

* Update the BranchShareLink shareURL when it is generated.

Update the shareURL correctly (AIS-331).

---

Branch-TestBed-Xcode-7/Branch-TestBed.xcodeproj/project.pbxproj
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
Branch-TestBed/module.modulemap
Branch.framework/Modules/module.modulemap
scripts/test-build-all

Removed residual CoreTelephony references.

---

Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed/Branch-TestBed/AppDelegate.m
ChangeLog.md

Fix push notification handling (GH #703).

---

Branch-SDK/Branch-SDK/BNCDeviceInfo.m
Branch-TestBed/Branch-TestBed.xcodeproj/xcshareddata/xcschemes/Branch-TestBed.xcscheme
ChangeLog.md

Fixed deviceInfo race condition (GH #700)

---

Branch-SDK/Branch-SDK/Branch.m
ChangeLog.md

Correctly handle Air Drop in continueUserActivity (GH-#699)

---

Branch-SDK/Branch-SDK/BNCEncodingUtils.m
Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed/Branch-TestBed/AppDelegate.m

Update Apple search ads mock-up for testing with partners and backend.

---

Branch-SDK/Branch-SDK/BNCDeviceInfo.m

Get user agent for iOS 7

---

Branch-SDK/Branch-SDK/BNCLog.h
Branch-SDK/Branch-SDK/BNCLog.m
Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed/Branch-SDK-Tests/BNCLog.Test.m
Branch-TestBed/Branch-TestBed.xcodeproj/xcshareddata/xcschemes/Branch-SDK-Tests.xcscheme
Branch-TestBed/Branch-TestBed.xcodeproj/xcshareddata/xcschemes/Branch-TestBed.xcscheme
Branch-TestBed/Branch-TestBed/AppDelegate.m

Initializing the log too early made the language bundles load in the wrong order.

Languages and Locale are reported wrong (GH-#707).

---

Branch-SDK/Branch-SDK/BNCEncodingUtils.h
Branch-SDK/Branch-SDK/BNCEncodingUtils.m
Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed/Branch-SDK-Tests/BNCEncodingUtils.Test.m

Fixed query string parsing for iOS 7 and added tests.

---

Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/NSString+Branch.h
Branch-SDK/Branch-SDK/NSString+Branch.m
Branch-TestBed/Branch-SDK-Tests/NSString+Branch.Test.m
Branch-TestBed/Branch-TestBed-UITests/TestBedUITests.m

Fix containsString crash iOS7 AIS-348.

---

Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/Networking/BNCServerInterface.m
Branch-SDK/Branch-SDK/Networking/BNCServerRequestQueue.m
Branch-TestBed/Branch-TestBed.xcodeproj/xcshareddata/xcschemes/Branch-SDK-Tests.xcscheme
Branch-TestBed/Branch-TestBed.xcodeproj/xcshareddata/xcschemes/Branch-TestBed.xcscheme

Fixes for iOS 11 and thread safety.

---

Branch-SDK/Branch-SDK/BranchActivityItemProvider.m
Branch-SDK/Branch-SDK/BranchShareLink.m
ChangeLog.md

Duplicate URL when sharing to clipboard (AIS-369, GH-#726).

---

Branch-SDK/Branch-SDK/BranchShareLink.h
Branch-SDK/Branch-SDK/BranchShareLink.m
Branch-SDK/Branch-SDK/BranchUniversalObject.h
Branch-SDK/Branch-SDK/BranchUniversalObject.m
Branch-TestBed/Branch-TestBed-UITests/UITestBed/TBBranchViewController.m
Branch-TestBed/Branch-TestBed-UITests/UITestBed/TBTableData.h
Branch-TestBed/Branch-TestBed-UITests/UITestBed/TBTableData.m
Branch-TestBed/Branch-TestBed/ViewController.m

Allow either bar button item or view for anchor.

Allow UIBarButtonItem or UIView as share presentation anchor AIS-360 AIS-376

---

Branch-SDK/Branch-SDK/BranchShareLink.m
Branch-SDK/Branch-SDK/BranchUniversalObject.m

Share always reports completed even when cancelled (AIS-395).

---

Branch-SDK/Branch-SDK/BNCLocalization.m
Branch-SDK/Branch-SDK/BNCLog.m
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.h
Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m
Branch-SDK/Branch-SDK/BranchConstants.m
Branch-SDK/Branch-SDK/BranchUniversalObject.m
Branch-SDK/Branch-SDK/BranchView.m
Branch-SDK/Branch-SDK/BranchViewHandler.m
Branch-SDK/Branch-SDK/Networking/BNCServerRequestQueue.h
Branch-SDK/Branch-SDK/Networking/BNCServerRequestQueue.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchCloseRequest.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchCreditHistoryRequest.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchSetIdentityRequest.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchSpotlightUrlRequest.m
Branch-TestBed/Branch-TestBed/AppDelegate.m
Branch-TestBed/Branch-TestBed/LogOutputViewController.m
Branch-TestBed/Branch-TestBed/ViewController.m

Fix more warnings discovered by setting -Weverything. Knocked off about 100.
I suppressed the availability warning for issue #740 too.

Fix or suppress warnings (GH-#740)

---

Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m

Fixed one missed v1 event upgrade.

---

README.md

Simple fix for the Swift syntax

Corrects readme using proper Swift syntax

---

Branch-TestBed-Swift/TestBed-Swift/AppDelegate.swift
Branch-TestBed-Swift/TestBed-Swift/ArrayTableViewController.swift
Branch-TestBed-Swift/TestBed-Swift/BranchUniversalObjectTableViewController.swift
Branch-TestBed-Swift/TestBed-Swift/CommerceEventDetailsTableViewController.swift
Branch-TestBed-Swift/TestBed-Swift/DictionaryTableViewController.swift
Branch-TestBed-Swift/TestBed-Swift/HomeViewController.swift
Branch-TestBed-Swift/TestBed-Swift/IntegratedSDKsData.swift
Branch-TestBed-Swift/TestBed-Swift/LinkPropertiesData.swift
Branch-TestBed-Swift/TestBed-Swift/LinkPropertiesTableViewController.swift
Branch-TestBed-Swift/TestBed-Swift/ProductArrayTableViewController.swift
Branch-TestBed-Swift/TestBed-Swift/WaitingViewController.swift
scripts/test-build-all

Updated testbed-swift to swift 4 string handling.

---

Branch-TestBed/Branch-TestBed/ViewController.m

* Added a link parameter for android/iOS testing.

Add Link Param

---

Branch-SDK/Branch-SDK/BNCSystemObserver.h
Branch-TestBed/Branch-SDK-Tests/BNCSystemObserver.Test.m
Branch-TestBed/Branch-TestBed-UITests/UITestBed.xcodeproj/project.pbxproj
Branch-TestBed/Branch-TestBed-UITests/UITestBed/Info.plist
Branch-TestBed/Branch-TestBed-UITests/UITestBed/TBAppDelegate.m
Branch-TestBed/Branch-TestBed-UITests/UITestBed/TBBranchViewController.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj

Added test for installDate / buildDate and fixed some UI.

---

Branch-TestBed-Swift/TestBed-Swift.xcodeproj/xcshareddata/xcschemes/TestBed-Swift.xcscheme
Branch-TestBed-Swift/TestBed-Swift/AppDelegate.swift
carthage-files/BranchSDK.xcodeproj/xcshareddata/xcschemes/Branch iOS SDK Carthage.xcscheme

Added some code for AppsFlyer integration.

---

Branch-SDK/Branch-SDK/BNCSystemObserver.m

Fix update / install status problem found by partner.

---

Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchUniversalObject.h
Branch-SDK/Branch-SDK/BranchUniversalObject.m
Branch-TestBed/Branch-SDK-Tests/BNCLog.Test.m
Branch-TestBed/Branch-SDK-Tests/BranchDelegate.Test.m
Branch-TestBed/Branch-SDK-Tests/BranchEvent.Test.swift
Branch-TestBed/Branch-TestBed-UITests/UITestBed.xcodeproj/project.pbxproj
Branch-TestBed/Branch-TestBed-UITests/UITestBed/Info.plist
Branch-TestBed/Branch-TestBed-UITests/UITestBed/TBAppDelegate.m
Branch-TestBed/Branch-TestBed-UITests/UITestBed/TBBranchViewController.m
Branch-TestBed/Branch-TestBed-UITests/UITestBed/UITestBed.entitlements
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
Branch-TestBed/Branch-TestBed.xcodeproj/xcshareddata/xcschemes/Branch-SDK-Tests.xcscheme
Branch-TestBed/Branch-TestBed.xcodeproj/xcshareddata/xcschemes/Branch-TestBed.xcscheme
Branch-TestBed/Branch-TestBed.xcodeproj/xcshareddata/xcschemes/Branch.xcscheme
Examples/WebViewExample/Podfile.lock

I fixed the Branch Universal Object so it always returning the new format.
Also, I confirmed that it is returning a format in parity with the Android object.
I updated the unit tests and the UITestBed app for testing.

Fixed Branch Universal Object & Update UITestBed

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m

Fix deadlock on iPhone 5 / iOS 9

---

Branch-SDK/Branch-SDK/BNCEncodingUtils.h
Branch-SDK/Branch-SDK/BNCEncodingUtils.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchLogoutRequest.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchOpenRequest.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchSetIdentityRequest.m

Check identity_id is a string - GH #783

---

Branch-TestBed-Swift/Podfile
Branch-TestBed-Swift/TestBed-Swift.xcodeproj/project.pbxproj
Branch-TestBed-Swift/TestBed-Swift/AppDelegate.swift
Branch-TestBed-Swift/TestBed-Swift/Info.plist

Added Crashlytics to the testbed.

Add Crashlytics DEVEX-114

---

Branch-SDK/Branch-SDK/BNCDebug.h
Branch-SDK/Branch-SDK/BNCDebug.m
Branch-SDK/Branch-SDK/BNCLog.h
Branch-SDK/Branch-SDK/BNCLog.m

Update header documentation

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m

* Don't make a what will result in a recursive call.
* Add another search directory.

Prefs crash fix DEVEX-258

---

Branch-SDK/Branch-SDK/BNCCommerceEvent.m
Branch-SDK/Branch-SDK/BNCFieldDefines.h
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/Networking/BNCNetworkService.h
Branch-SDK/Branch-SDK/Networking/BNCNetworkService.m

Silence some code analyzer warnings.

---

Branch-SDK/Branch-SDK/BNCURLBlackList.m
Branch-SDK/Branch-SDK/Networking/BNCServerInterface.m

Handle network service deallocation better.

---

Branch-TestBed/Branch-TestBed-UITests/UITestBed/Info.plist
Branch-TestBed/Branch-TestBed-UITests/UITestBed/TBBranchViewController.m

For testing rewards in UITestBed.

Add rewards tests to UITestBed

---

Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchShareLink.m

Updated sharing events to fire.

---

Branch-SDK/Branch-SDK/BNCURLBlackList.m
Branch-SDK/Branch-SDK/Networking/BNCNetworkService.m

Don't print HTTP status 404 error pages because it looks like an error.

---

Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.h
Branch-SDK/Branch-SDK/BranchCSSearchableItemAttributeSet.m

Import Foundation First

---

Branch-TestBed-Swift/TestBed-Swift/AppDelegate.swift

Automatic Reattribution for Adjust through Universal links and URI schemes.

ATAN-523 Code snippets for Adjust reattribution

---

Branch-SDK/Branch-SDK/BNCSystemObserver.m
README.md

* Updated our URI scheme filter that finds a URI scheme for the partner's app.
* Updated the docs to clarify that the partner's app URI should be the first URI.
@sojanpr @Sarkar

Updated URI Filter and Docs DEVEX-343

---

Branch-TestBed-Swift/TestBed-Swift/AppDelegate.swift

https://branch.atlassian.net/browse/DEVEX-327
https://fabric.io/branch-metrics/ios/apps/io.branch.testbed-swift/issues/5acd261736c7b23527213313?time=1523318400000%3A1523404799000

fix-swift-testbed-crash-DEVEX-327

---

Branch-TestBed-Swift/TestBed-Swift/CommerceEventTableViewController.swift

Added Adjust revenue Event tracking in testbedSwift

Tracking Revenue Events through Adjust

---

Branch-TestBed/README.md
Examples/UITestBed/UITestBed-UITests/Info.plist
Examples/UITestBed/UITestBed-UITests/UITestBed.strings
Examples/UITestBed/UITestBed-UITests/UITestEvents.m
Examples/UITestBed/UITestBed-UITests/UITestSafari.m
Examples/UITestBed/UITestBed.xcodeproj/project.pbxproj
Examples/UITestBed/UITestBed.xcodeproj/xcshareddata/xcschemes/UITestBed.xcscheme
Examples/UITestBed/UITestBed/TBAppDelegate.m
Examples/UITestBed/UITestBed/TBBranchViewController.m
Examples/UITestBed/UITestBed/TBDetailViewController.m
Examples/UITestBed/UITestBed/TBDetailViewController.xib
Examples/UITestBed/UITestBed/TBSettings.h
Examples/UITestBed/UITestBed/TBSettings.m
Examples/UITestBed/UITestBed/TBTableData.h
Examples/UITestBed/UITestBed/TBTableData.m

Updated the UITests for easier automated testing.

---

Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchOpenRequest.m
Examples/UITestBed/UITestBed/TBAppDelegate.m

DEVEX-706 Fix occasional double open.

---

Branch-SDK/Branch-SDK/BranchActivityItemProvider.m
Branch-SDK/Branch-SDK/BranchShareLink.m
Branch-SDK/Branch-SDK/BranchUniversalObject.m

Added Apple Reminders as a scraper to prevent deferred linking.

DEVEX-775 Add preview link scraping for Apple Reminders

---

Branch-SDK-Tests/BNCEncodingUtils.Test.m
Branch-SDK/Branch-SDK/BNCEncodingUtils.h
Branch-SDK/Branch-SDK/BNCEncodingUtils.m
Branch-SDK/Branch-SDK/Branch.m
Examples/UITestBed/UITestBed/TBBranchViewController.m

* Fix JSON string encoding so that Facebook auth works right. 
* Update unit tests.

DEVEX-816 Facebook URI Fix

---

README.md

README: Fix the restorationHandler closure signature 

---

Branch-SDK/Branch-SDK/BNCConfig.m
Branch-TestBed/Branch-TestBed/Branch-TestBed-Info.plist

Update url to https://api2.branch.io
Enable ATS in the testbed app

DEVEX-808 change url and enable ATS

---

Branch-SDK/Branch-SDK/Branch.h
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
carthage-files/BranchSDK.xcodeproj/project.pbxproj

Add include BranchCSSearchableItemAttributeSet to Branch.h closing #873

---

Branch-SDK/Branch-SDK/BNCConfig.m
Branch-TestBed/Branch-TestBed/Branch-TestBed-Info.plist

Reverts BranchMetrics/ios-branch-deep-linking#872
This needs to wait until the api2 endpoint is stable.

Revert "DEVEX-808 change url and enable ATS"

---

Branch-SDK/Branch-SDK/BNCCommerceEvent.h
Branch-SDK/Branch-SDK/BNCCommerceEvent.m
Branch-SDK/Branch-SDK/BNCLinkData.h
Branch-SDK/Branch-SDK/BNCLinkData.m
Branch-SDK/Branch-SDK/BranchEvent.h
Branch-SDK/Branch-SDK/BranchEvent.m
Branch-SDK/Branch-SDK/Networking/BNCServerRequest.h
Branch-SDK/Branch-SDK/Networking/BNCServerRequest.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchCreditHistoryRequest.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchRedeemRewardsRequest.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchRegisterViewRequest.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchSetIdentityRequest.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchShortUrlRequest.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchUserCompletedActionRequest.h
Branch-SDK/Branch-SDK/Networking/Requests/BranchUserCompletedActionRequest.m

DEVEX-837 Updated the SDK to use secure coding.

---

Branch-SDK-Tests/BNCServerRequestQueueTests.m
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/Networking/BNCServerInterface.m
Examples/UITestBed/UITestBed/TBAppDelegate.m

* Added new network error check.
* Updated queue handling for continueUserActivity.

DEVEX-850 iOS 12 Background Networking Change

---

Branch-SDK-Tests/BNCDeviceInfo.Test.m
Branch-SDK-Tests/BNCLog.Test.m
Branch-SDK-Tests/BNCServerRequestQueueTests.m
Branch-SDK-Tests/BNCTestCase.h
Branch-SDK-Tests/BNCTestCase.m
Branch-SDK-Tests/BNCURLBlackList.Test.m
Branch-SDK-Tests/BranchGetCreditHistoryRequestTests.m
Branch-SDK-Tests/BranchInstallRequestTests.m
Branch-SDK-Tests/BranchOpenRequestTests.m
Branch-SDK-Tests/BranchRedeemRewardsRequestTests.m
Branch-SDK-Tests/BranchShortUrlRequestTests.m
Branch-SDK-Tests/BranchShortUrlSyncRequestTests.m
Branch-SDK-Tests/BranchUniversalObject.Test.m
Branch-SDK-Tests/BranchUserCompletedActionTests.m
Branch-SDK/Branch-SDK/BNCStrongMatchHelper.h
Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m
Branch-SDK/Branch-SDK/Networking/BNCServerRequestQueue.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
Branch-TestBed/Branch-TestBed.xcodeproj/xcshareddata/xcschemes/Branch-TestBed.xcscheme

Unit tests were inconsistently failing and succeeding, mostly due to assumed app state. This PR fixes some of that.
Also, I think that iOS 12 unearthed some latent race condition bugs too.

DEVEX-861 Fix inconsistent unit tests.

---

Branch-SDK/Branch-SDK/BNCConfig.m
Branch-TestBed/Branch-TestBed/Branch-TestBed-Info.plist

DEVEX-808 change url and enable ATS [Do Not Merge]

---

Branch-SDK/Branch-SDK/Branch.h
README.md

Updated header doc and README for `openURL:options:` use.

---

Branch-SDK-Tests/BNCURLBlackList.Test.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj

* Black list unit test was failing on installs.
* This time merging to staging instead of master!

DEVEX-826 Fix Unit Tests

---

Branch-SDK/Branch-SDK/Branch+Validator.m

Fixed a crash bug in the validator code.

GH-892 Fix Validator Error

---

.circleci/config.yml
.gitignore
Branch-SDK-Tests/BNCServerInterface.Test.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
Branch-TestBed/Gemfile
Branch-TestBed/fastlane/Appfile
Branch-TestBed/fastlane/Fastfile
Branch-TestBed/fastlane/Matchfile

First version of CircleCI.  This works but is really basic.
We have a couple flakey tests, if you see a failure.  Please retry.

SDK-150 circle ci support

---

Branch-SDK/Branch-SDK/BNCEncodingUtils.m
Branch-TestBed/Branch-SDK-Unhosted-Tests/BNCEncodingUtilsTests.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj

Protect against bad access error due to unexpected key type.  Also log the type coming in.

INTENG-6187 bad access crash 

---

.gitlab-ci.yml
README.md

Enable gitlab runner on mac mini
@echo-branch @hubt

Enable gitlab runner on mac mini

---

Branch-SDK/Branch-SDK/Branch.m

This is a quick fix for the issue.  I really want to refactor this as the current solution is difficult to maintain.

INTENG-7729 race condition with search ads or slow init

---

Branch-SDK/Branch-SDK/Branch.h

Cleaning up the nullability warnings.  Think I got them all.

SDK-517 first pass at nullability in Branch.h

---

Branch-SDK-Tests/BranchOpenRequestTests.m
Branch-SDK/Branch-SDK/BNCTuneUtility.h
Branch-SDK/Branch-SDK/BNCTuneUtility.m
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchOpenRequest.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj

Repurposes the deprecated update flag with tune migration status information.

INTENG-7695 check for tune

---

Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed-Swift/TestBed-Swift/AppDelegate.swift
Branch-TestBed-Swift/TestBed-Swift/CommerceEventDetailsTableViewController.swift
Branch-TestBed-Swift/TestBed-Swift/CommerceEventTableViewController.swift
Branch-TestBed-Swift/TestBed-Swift/CustomEventTableViewController.swift
Branch-TestBed-Swift/TestBed-Swift/HomeViewController.swift
Branch-TestBed-Swift/TestBed-Swift/ReferralRewardsTableViewController.swift
carthage-files/BranchSDK.xcodeproj/project.pbxproj

Fixes some nullability information.  getInstance can no longer return nil.

SDK-554 Fixes for swift project

---

Branch-SDK/Branch-SDK/Branch.m

Maintain existing error handling behavior.  I think this is a little aggressive, but it's consistent with previous behavior.
The only change is that we now log a warning that a method that requires initialization was called before init.

SDK-631 add workaround for error state handling

---

Branch-SDK-Tests/BNCFacebookAppLinksTests.m
Branch-SDK/Branch-SDK/BNCFacebookAppLinks.m

Just reworking the FB unit test to be a little simpler.

SDK-686 simplify FB unit test

---

Branch-SDK-Tests/BranchEvent.Test.m

Missed a test when reviewing this.

SDK-696 fix tests for mutability change on branch event

---

Branch-SDK/Branch-SDK/Branch.m

Missed this ! which leads to subtle but severe issues.  :(

SDK-720 fix shortlink issue

---

Branch-SDK/Branch-SDK/BranchShareLink.h
Branch-SDK/Branch-SDK/BranchShareLink.m
Branch-TestBed/Branch-TestBed/AppDelegate.m

This does not have any unit tests as it's a UI change.  We should eventually add more UI tests.

INTENG-8456 allow overriding the placeholder url

---

Branch-SDK-Tests/BNCEncodingUtils.Test.m
Branch-SDK/Branch-SDK/BNCEncodingUtils.m
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchOpenRequest.m

I can demo the suspected root cause on a test app, I wasn't able generate a good unit test for it.

INTENG-8944 rare open crash

---

Branch-SDK/Branch-SDK/Branch.m

INTENG-8758 restore previous callback on main behavior

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch.podspec

Logging updates

---

Branch-SDK/Branch-SDK/Branch.h
Branch-TestBed-Swift/Podfile
Branch-TestBed-Swift/TestBed-Swift.xcodeproj/project.pbxproj

Missed adding the BranchScene.h to the umbrella header.  This is preventing Carthage users from accessing that class.

SDK-957 add BranchScene to umbrella header

---

Branch-SDK/Branch-SDK/BNCKeyChain.m

SDk-961 limit query to Branch saved values

---

Branch-SDK/Branch-SDK/NSError+Branch.m

I failed to copy paste this correctly when refactoring a while back.

SDK-989 correct misleading error message

---

Branch.podspec

Clean up pod description

---

Branch-SDK/Branch.m
Branch-SDK/BranchJsonConfig.h
Branch-SDK/BranchJsonConfig.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
Branch-TestBed/Branch-TestBed/Branch-TestBed-Info.plist

Add files to interpret and implement branch.json

Add files to interpret and implement branch.json

---

Branch-SDK/BNCServerInterface.m
Branch-SDK/Branch.m
Branch-SDK/BranchEvent.m
Branch-SDK/BranchOpenRequest.m
Branch-TestBed/Branch-SDK-Tests/BNCAppleAdClientTests.m

Back porting a couple fixes for a patch release.

INTENG-11208 patch release review

---

Branch-SDK/BNCServerInterface.m
Branch-SDK/Branch.m
Branch-SDK/BranchJsonConfig.m

In an Opt In situation, do not reject calls that don't have an install event.

INTENG-11208 on opt in do not check for install

---

Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/BNCServerInterface.m
Branch-TestBed/Branch-SDK-Tests/BNCPreferenceHelperTests.m

Change default behavior to not send close requests.

CORE-1354 switch default to not send close requests

---

Branch-SDK/BNCServerInterface.m
Branch-SDK/Branch.h
Branch-SDK/Branch.m
Branch-SDK/NSError+Branch.m

Totally missed a term in the first attempt to fix this. This does change a little used public API.

CORE-1626 missed a term

---

Branch-SDK/Branch.h
Branch-SDK/Branch.m
Branch-SDK/BranchLastAttributedTouchData.h
Branch-SDK/BranchLastAttributedTouchData.m

SDK-1111 support error return for latd method

---

Branch-SDK/BNCAppGroupsData.m

Remove log messages from App Clips.

CORE-1753 remove debug messages, they trigger security scanners

---

Branch-SDK/Branch.h

Clarify header docs to avoid confusion.

CORE-1808 clarify header documentation.

---

Branch-SDK/Branch.h
Branch-SDK/Branch.m
Branch-SDK/BranchEvent.h
Branch-SDK/BranchEvent.m
Branch-TestBed/Branch-SDK-Tests/BranchEvent.Test.m

A public API to help measure ATT prompt performance.

CORE-1768 att opt in dialog event

---

Branch-TestBed/Branch-SDK-Tests/BNCAppleAdClientTests.m
Branch-TestBed/Branch-SDK-Tests/BNCAppleSearchAdsTests.m

CORE-1946 fix unit tests for old Apple Search Ads

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Deleting the `staging` branch while there are no open pull requests. Please submit all future pull requests to `master` (the default branch anyway).

PRs to be opened against master

---

Branch-SDK/BNCPreferenceHelper.m

Dictionary is failing to deserialize

CORE-2502 rollback to old serialization

---

.github/workflows/release.yml

Add the no idfa binaries to the release script

CORE-2483 update build upload to include prebuild no idfa frameworks

---

Branch-SDK/BranchOpenRequest.m
Branch-TestBed/Branch-SDK-Tests/BranchOpenRequestTests.m

Removed the check to see if storedParams is empty and now only checking isInstall

[SDK-1363] Changed the check for installParams

---

Branch-SDK/BNCPreferenceHelper.m
Branch-TestBed/Branch-SDK-Tests/BNCPreferenceHelperTests.m

SDK-1199 fix missed serialization class type

---

Package.swift

Thanks soumyamahunt!
A long forgotten PR to the SPM repo. I keep forgetting about.
https://github.com/BranchMetrics/ios-branch-sdk-spm/pull/6

SDK-1450 copy over PR from SPM repo

---

Branch-SDK/BNCServerInterface.m
Branch-SDK/BranchConstants.m
Branch-TestBed/Branch-SDK-Tests/BNCServerInterface.Test.m

--  Updated param name referrer_gbraid to gbraid
-- It should only be included on v2/events.

SDK-1461 -- [iOS] Updates to GBRAID handling.

---

.github/PULL_REQUEST_TEMPLATE.md

Added a template file for new pull requests. It's open to future changes based on feedback and suggestions from the team.

Created template for PRs

---

README.md

Use Branch Link for Sandbox Program sign-ups
https://branch.link/sandbox?~channel=ios-repo

Use Branch Link for Sandbox Program sign-ups

---

.github/dependabot.yml

SDK-1770 -- implement dependabot for ios-sdk repo
Add Dependabot to this repo to check and automate dependencies for :
- Github Actions
**Note** : Currently there’s no support for IOS projects package managers.Plan to support swift package manager was recently shelved.

SDK-1770 : Create dependabot.yml

---

Branch-TestBed/Branch-SDK-Tests/BNCTestCase.m
Branch-TestBed/Branch-TestBed/AppDelegate.m
Branch-TestBed/Branch-TestBed/LogOutputViewController.m
Branch-TestBed/Branch-TestBed/Main.storyboard
Branch-TestBed/Branch-TestBed/ViewController.m

SDK-1744 -- [iOS] Update iOS Testbed
Updated the UI, removed old functions, and added new functions to the testbed. 
The old testbed UI became dated and some of the functionality was either deprecated or missing.
Run the testbed and try the various methods through the buttons.

[SDK-1774] Update iOS Testbed

---

.github/workflows/post-release-qa.yml
.github/workflows/release.yml

SDK-1762 -- Release Automation
https://branch.atlassian.net/browse/SDK-1762
Minor change  - updated user name to branchlet and removed trigger push trigger type from .github/workflows/post-release-qa.yml script.
Couldn't test all changes now. The change is part of script which creates a new Release. So we will test it when we will create next Release.  Please just verify if the username is correct and .github/workflows/post-release-qa.yml will not trigger on push.

Updated User name and trigger type

---

Branch-TestBed/Branch-SDK-Tests/BranchSetIdentityRequestTests.m
BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
BranchSDK/BNCConfig.m
ChangeLog.md
scripts/version.sh

SDK-1980 - Release 2.2.0
Updated changedlog.md, bumped version from 2.1.2 to 2.2.0, and removed commented out code.
Update the SDK to a new version.
[SDK-1980]: https://branch.atlassian.net/browse/SDK-1980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-1980] Release 2.2.0

---

.github/workflows/verify.yml
Gemfile

Fixes issue with GHA verify.yaml failing with error 
`bundler: failed to load command: fastlane `
Seems to be an issue with the latest version of activesupport so changed it back to last stable version

ci(gha): Fix bundler: failed to load command: fastlane

---

.github/workflows/dependabot-merger.yml

The update changes the Dependabot merger Github Action to use github-script instead of shell commands. It now also creates a PR with the combined changes instead of just opening a branch.
The old action was flaky and hard to understand, so this updates it to use a more consistent workflow.
Run the script manually and observe the new PR it creates and sends a slack message in #sdk-pr-reviews.

[SDK-2032] Fix dependabot merger

---

.github/workflows/automation-trigger-test.yml

SDK-iOS build response key changes
Removed reference to non-master branch in GHA for appium tests.
[ ] Bug fix (non-breaking change which fixes an issue)
Check all appium tests are passed and verify from GHA logs, source code was checked out from master branch.

Update browser stack env variable

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
ChangeLog.md
Sources/BranchSDK/BNCConfig.m
scripts/version.sh

SDK-2240 Prep iOS 3.2.0 release
Update changelog and version
Confirm changelog and version changes look ok

Prep iOS release 3.2.0

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
ChangeLog.md
Sources/BranchSDK/BNCConfig.m
scripts/version.sh

v.3.4.0
- Added support for setting the Branch API base URL through the `branch.json` file.

Release 3.4.0

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
ChangeLog.md
Sources/BranchSDK/BNCConfig.m
scripts/version.sh

SDK-2350 iOS SDK 3.4.1
Collection of bugfixes and logging improvements.

Prep iOS 3.4.1 release 

---

.github/workflows/release.yml

SDK-2351 fix release script
Fix iOS script by bringing upload to v4

SDK-2351 Update upload to v4 to match the download

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
ChangeLog.md
Sources/BranchSDK/BNCConfig.m
scripts/version.sh

v.3.4.4
- Fix for rare case where Branch events were duplicated
- Fixed script in "Run Script" phase of static framework targets

Release 3.4.4

---

Sources/BranchSDK/BNCPreferenceHelper.m
Sources/BranchSDK/BNCReferringURLUtility.m
Sources/BranchSDK/BNCServerInterface.m
Sources/BranchSDK/Branch.m

Add trace logging

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
ChangeLog.md
Sources/BranchSDK/BNCConfig.m
scripts/version.sh

Release 3.5.0

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
ChangeLog.md
Sources/BranchSDK/BNCConfig.m
scripts/version.sh

Release 3.5.1

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
ChangeLog.md
Sources/BranchSDK/BNCConfig.m
scripts/version.sh

v.3.6.0
- Bug fix with universal links on cold opens

Release 3.6.0

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
ChangeLog.md
Sources/BranchSDK/BNCConfig.m
scripts/version.sh

- Fixed issues where external_intent_uri was incorrectly set in certain cases

Release 3.6.1

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
ChangeLog.md
Sources/BranchSDK/BNCConfig.m
scripts/version.sh

- Added new `BranchAdvancedLogCallback` which contains request and response data for Branch network requests
- Added ability to set Consumer Protection Attribution Level through the `branch.json` file

Release 3.8.0

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
ChangeLog.md
Sources/BranchSDK/BNCConfig.m
scripts/version.sh

Release 3.9.1 Version and ChangeLog Updates.

Release 3.9.1 Version and ChangeLog Updates.

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
ChangeLog.md
Sources/BranchSDK/BNCConfig.m
scripts/version.sh

Release 3.10.0 Version and Change Log Updates

Release 3.10.0 Updates
