BranchMetrics/ios-branch-deep-linking-attribution

Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchActivityItemProvider.m

Adds Branch class methods which return a UIActivityItemProvider subclass, with arguments for Branch params and properties. The subclass generate a Branch short URL that is auto tagged with the channel based on the sharing activity  the user selected. The callback for the short URL is fired on a thread other than the main thread, however, the main thread waits for the callback to return and provide the UIActivityItem. This implementation boils down sharing Branch URLs with a UIActivityView share sheet to just a few lines of code.

UIActivityItemProvider Subclass

---

Branch-SDK/Branch-SDK/BNCConfig.h
Branch-SDK/Branch-SDK/BNCServerInterface.m
Branch-TestBed/Branch-SDK Stubless Tests/Branch_SDK_Stubless_Tests.m
Branch.podspec
ChangeLog.md

Large rework of `BNCServerInterface encodePostToUniversalString:needSource:]` method.
* Removing spaces at start/end of object, since they're not in the middle anyway. No need for extra bytes for those two spaces.
* Rather than executing `[params objectForKey:]` a dozen times inside the for loop, just storing off into a local var.
* Updating encoding of nested dictionaries to *not* include source attribute. Doesn't make sense to add this at any level other than root.
* Adding support for null (and adding note to add more support in the future).
* Adding `continue` in else case for types. If we haven't encoded it at this point, we end up trying to append nil which causes the crash mentioned in BranchMetrics/Branch-iOS-Invite-SDK#19.
* Cleaning up append calls, no need to have so many -- a …

[BNCServerInterface encodePostToUniversalString] cleanup

---

Branch-SDK/Branch-SDK/BNCConfig.h
Branch-SDK/Branch-SDK/BNCLinkData.m
Branch.podspec
ChangeLog.md

@aaustin @shortstuffsushi 
Fixing issue described in https://coderwall.com/p/gcwpua/beware-of-nsstring-hash

Convert params to md5 (32 fixed length) before hashing

---

Branch-SDK/Branch-SDK/BNCSystemObserver.h
Branch-SDK/Branch-SDK/BNCSystemObserver.m
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchServerInterface.m

@aaustin @derrickstaten @qinweigong @Sarkar
Previously, this was being updated when a get was called, which feels somewhat unnatural.
Additionally, in the case of an install or open "failing," the update state shouldn't be updated.
UpdateState should only be set when the open/install call completes successfully.

Separating set/get of update state.

---

Branch-SDK/Branch-SDK/Branch.m

Returning User URL by itself isn't correct, but you can add all the params and make it a long url.
Note that we don't have the items available in the handleFailure: method, so we don't even try (also note this won't be the case in the callbacks branch).
Updating generateLongUrl to share the same method, since they're accomplishing the same thing.

Adding long User URL to getShortUrl failure logic.

---

Branch-SDK/Branch-SDK/BNCLinkCache.h
Branch-SDK/Branch-SDK/BNCServerInterface.h
Branch-SDK/Branch-SDK/BNCServerInterface.m
Branch-SDK/Branch-SDK/BNCServerRequest.h
Branch-SDK/Branch-SDK/BNCServerRequest.m
Branch-SDK/Branch-SDK/BNCServerResponse.h
Branch-SDK/Branch-SDK/BNCSystemObserver.m
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchServerInterface.m

The Link Data object no longer needs to be passed to and from the server interface. The callbacks mean that it can stay within the scope of the actual method using it.

Dont pass around link data

---

Branch-SDK/Branch-SDK/BNCLinkData.h
Branch-SDK/Branch-SDK/BNCLinkData.m
Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchServerInterface.m

Updating LinkData items (constants, enum) to be in the proper header file.
Removing setObject:forKeyedSubscript: which isn't needed.

LinkData cleanup

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/BNCServerInterface.h
Branch-SDK/Branch-SDK/BNCServerInterface.m
Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchServerInterface.h
Branch-SDK/Branch-SDK/BranchServerInterface.m
Branch-TestBed/Branch-SDK Functionality Tests/BNCPreferenceHelperTests.m
Branch-TestBed/Branch-SDK Functionality Tests/BNCServerInterfaceTests.m
Branch-TestBed/Branch-SDK Functionality Tests/BranchNetworkScenarioTests.m
Branch-TestBed/Branch-SDK Functionality Tests/Branch_SDK_Functionality_Tests.m
Branch-TestBed/Branch-SDK Load Tests/Branch_SDK_Load_Tests.m

Rather than letting BNCServerInterface choose a key, it should be provided with one for each request.
This means adding key to all the methods (yay, more injection).
Prior to this change, when trying to use test mode, the server interface would never have actually sent the test key.
Not entirely confident that the Preference helper is doing this right, but that's going to be another change.
Also removed some unused methods from the BranchServerInterface.
Consolidated param prep within BNCServerInterface into a single method.

Fix key usage

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.h
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchServerInterface.m
Branch-TestBed/Branch-SDK Functionality Tests/BNCPreferenceHelperTests.m
Branch-TestBed/Branch-TestBed/AppDelegate.m

Updating PreferenceHelper debug to only use two booleans, once indicating whether the app is in debug mode, when indicating with it is connected to remote debug.
Removing bnc_ prefixes from a bunch of methods in Branch.m.
Making all the variables related to debug instance variables (and setDebug an instance method).
Updating open/install debug checks to just use `isDebug`.

Rework debug logic

---

Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m

Making it possible for developers to understand whether Branch has a developer identity set for this User.
Previously, it wasn't possible for developers to know if Branch already had a developer identity set for a User, which persists through installs.

Expose Identity State

---

Branch-SDK/Branch-SDK/BNCSystemObserver.m
Branch-TestBed/Branch-SDK Functionality Tests/BNCSystemObserverTests.m

@derrickstaten 
Change update state check to one day to account for "long downloads" which may cause the doc dir and bundle to have > 1 min difference in timestamp.

Update Update State

---

Branch-SDK/Branch-SDK/BNCEncodingUtils.h
Branch-SDK/Branch-SDK/BNCEncodingUtils.m
Branch-SDK/Branch-SDK/BNCLinkData.m
Branch-SDK/Branch-SDK/BNCServerInterface.m
Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed/Branch-SDK Functionality Tests/BNCEncodingUtilsTests.m
README.md

Source shouldn't be added to every dictionary that is encoded, it should only be added where desired. Specifically, it should be added to url generation, where the creation source is present.

Dont add source in encoding

---

Branch-SDK/Branch-SDK/BNCLinkData.h
Branch-SDK/Branch-SDK/BNCLinkData.m
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchShortUrlRequest.m
Branch-TestBed/Branch-SDK Functionality Tests/BNCEncodingUtilsTests.m

@qinweigong 
Just keeping params a dictionary until it actually needs to be converted. This prevents the encoding from happening twice.

Double encoded params

---

Branch-SDK/Branch-SDK/BNCServerRequestQueue.h
Branch-SDK/Branch-SDK/BNCServerRequestQueue.m
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchOpenRequest.h
Branch-SDK/Branch-SDK/BranchOpenRequest.m
Branch-TestBed/Branch-SDK Functionality Tests/BNCServerRequestQueueTests.m
Branch-TestBed/Branch-SDK Functionality Tests/BranchNetworkScenarioTests.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj

@derrickstaten 
When an Open/Install request is persisted to disk, its callback is lost.
This means that even when it is actually executed, the Branch file is never informed of the update, and never marks itself as initialized.
Now, we always re-add the callback to make sure that link is still in place.

Dissociative Callbacks

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchActivityItemProvider.h
Branch-SDK/Branch-SDK/BranchActivityItemProvider.m
README.md

@qinweigong @francisjervis
This pull request adds the ability for devs to change the items used to create the short url based on the channel the user chooses.
Additionally, this allows the dev to override the "human readable channel" that Branch automatically uses (for instance, you could use "fb" instead of "facebook" or something like that).
It also re-organizes the Branch interface so the ordering is more logical.
```
- (id)foo;
- (id)foo:bar;
- (id)foo:bar:baz;
```
Instead of
```
- (id)foo;
- (id)foo:baz:bar;
- (id)foo:bar;
```

Delegate for activity item

---

Branch-SDK/Branch-SDK/BranchCreditHistoryRequest.m

@aaustin 
Fixed this once before, but must have been lost in a merge. This is what actually caused the bug in the Invite SDK. I'll probably go through and revert those checks in that SDK, as they will be redundant.

Fixing bad key used for object removal.

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/BranchOpenRequest.m

@aaustin 
Because the JSON parser is naive to what types it's getting back, it seems there are cases where they identity can become a number.
To avoid this, we are now checking on both the set/get sides to ensure the type we expect comes through.

Identity Type Mixup

---

Branch-SDK/Branch-SDK/BranchUpdateAppListRequest.h
Branch-SDK/Branch-SDK/BranchUpdateAppListRequest.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj

Crashes are being reported when the update app list server request was
persisted pre-removal, then being retrieved post-removal. We need to
leave this in for a while so that we can retrieve the queue from disk.
@qinweigong

Urgent: Add back in update app list

---

Branch-SDK/Branch-SDK/BranchActivityItemProvider.m

@qinweigong @aaustin 
Not sure how this was working in the past, but apparently simply putting the constants inside of a version check isn't enough -- they cause a crash because they aren't defined at all for iOS 6.
This also made it apparent that we're doing an == check on strings, updated accordingly.

Conditionally defining constants for iOS 6.

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.h
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m

@derrickstaten 
Since there is a desire to use non-whole second timeouts, just changed to using NSTimeIntervals.
TimeIntervals are typedef'd as doubles, so they allow non-whole numbers.
Since this is the type the NSURLRequest is expecting anyway, it's a pretty easy change to make.

Use Time Intervals

---

Branch-SDK/Branch-SDK/BNCDebugRequest.h
Branch-SDK/Branch-SDK/BNCDebugRequest.m
Branch-SDK/Branch-SDK/BNCError.h
Branch-SDK/Branch-SDK/BNCServerRequestQueue.m
Branch-SDK/Branch-SDK/BNCSystemObserver.m
Branch-SDK/Branch-SDK/BranchConnectDebugRequest.h
Branch-SDK/Branch-SDK/BranchDisconnectDebugRequest.h
Branch-SDK/Branch-SDK/BranchLogRequest.h
Branch-SDK/Branch-SDK/BranchLogRequest.m
Branch-TestBed/Branch-SDK-Tests/BNCServerRequestQueueTests.m
Branch-TestBed/Branch-SDK-Tests/BNCSystemObserverTests.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj

@qinweigong @Sarkar 
Persist the log when for log requests, so they can be restored (potentially causing nil in dictionary).

Remove Debug Requests from Persistence

---

Branch-SDK/Branch-SDK/BNCContentDiscoveryManager.h
Branch-SDK/Branch-SDK/BNCContentDiscoveryManager.m
Branch-SDK/Branch-SDK/Branch.m

@aaustin this only works if the dev initializes the NSUserActivity with type `CSSearchableItemActionType`. And the identifier I get back is not human readable. I got back `Hi2Ue7xN+tdtb6W6gyae2g==` from `userActivity.userInfo[CSSearchableItemActivityIdentifier]`. So while we can send this up, I'm not sure what's going on or how helpful it will be.

capture non-branch spotlight identifiers

---

Branch-SDK/Branch-SDK/Branch.m
README.md

@aaustin please leave on branch until ready for release. Now that we've added handling for race conditions that presumably were not an issue before this, I need to go test that removing the `load` call doesn't re-break any functionality.

remove codeless install

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.h
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/Requests/BranchLoadRewardsRequest.m

If response dictionary has length (1 or more buckets for credits), update shared prefs with the values, otherwise, user has no reward history. Set count to 0 for default bucket. 

Clear credits on logout

---

Branch-SDK/Branch-SDK/BNCContentDiscoveryManager.h
Branch-SDK/Branch-SDK/BNCContentDiscoveryManager.m
Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchUniversalObject.m
Branch-TestBed/Branch-TestBed/Base.lproj/Main.storyboard
Branch-TestBed/Branch-TestBed/UniversalObjectViewController.h
Branch-TestBed/Branch-TestBed/UniversalObjectViewController.m

Concerted effort to pass through the expiration date from the partner API to Spotlight.  This required far more changes than it ought to have.
In the end, although it -appears- that everything is correctly configured, the items do not get flushed from Spotlight, despite the correct date appearing in the mdItemExpirationDate field of the CSSearchItem.
I'm checking this in on a floating branch for further investigation.

Pass content expiration date through to spotlight index

---

Branch-SDK/Branch-SDK/BNCSystemObserver.m
Branch-TestBed/Branch-TestBed/Branch-TestBed-Info.plist

We need to have a discussion about this; it seems that Apple broke access to poking around in the kSecClass:  classes, (iOS 92. latest Xcode) which we were using to get the Team ID.
I found another way, but it requires the partner to add a key to their plist.

Proposed small fix to get the team identifier working in iOS 9.2

---

Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m

@danwalkowski for developers who use the latest Facebook SDK and want to allow it to return `NO` for `application:didFinishLaunchingWithOptions:`. Tested by both myself and the Gogobot team, this works.

Account for fb

---

Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m

@aaustin @ahmednawar we should not have any versions of initSession that don't pass in launchOptions. This will only cause confusion. Our SDK does not function normally without launchOptions.
If anyone is using one of these methods and upgrades SDKs, they will need to switch to a more complete version of initSession. While I in general am highly opposed to forced upgrades, anyone currently using one of these methods has a buggy implementation of Branch.

launchOptions are required

---

Branch-SDK/Branch-SDK/BranchUniversalObject.m

This fixes https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/issues/297
It's safe to hide deprecation warnings on this line as the new completion handler is checked for above.
Cheers!

fix deprecation warning when targeting iOS 8

---

Branch-SDK/Branch-SDK/BNCServerInterface.m

@ahmednawar @derrickstaten When the retry code executes due to a 500
error code, we fall through and callback the block. This should not
happen and would lead to callbacks being executed multiple times. I
believe this to be the root cause of the crash when the credit service
went down last night.

Fix retry code

---

Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m

`NSURL` returns `nil` if the string is an invalid URL. If a partner uses a space in their app version, this would return `nil` for example. `SFSafariViewController` crashes if given a `nil` for a URL. This change encodes the request and ensure it fails gracefully if the URL is `nil` for any reason.
2 things worth checking that I am not sure how to check for: ensuring that an encoded request would work fine on the backend (the logs are fine) and implications on the request queue on the client when returning early. I set `self.requestInProgress = NO` but not sure if this is enough.
@aaustin @derrickstaten @scott-branchio

add sanity checks to strong_match request url

---

Branch.podspec

As a developer I would like to be able to install the SDK using CocoaPods and without the AdSupport framework (IDFA).
In the docs you pin point correctly [how to achieve this](https://dev.branch.io/getting-started/sdk-integration-guide/guide/ios/#submitting-to-the-app-store).
I added a new subspec in the podspec that any developer will be able to use for installing the SDK without IDFA. This will allow us to keep the SDK updated easily.
For testing it you can include this line in a test project: `pod 'Branch/without-IDFA', git: 'https://github.com/ziogaschr/iOS-Deferred-Deep-Linking-SDK.git', :branch => 'cocoapod-without-idfa'`
p.s.: `idfa.source_files` at line 31 is needed as having only the `idfa. frameworks ` at line 33 is not sufficient.

Add CocoaPods subpec that doesn't add AdSupport (IDFA)

---

Branch-SDK/Branch-SDK/Branch.m

As reported in https://github.com/BranchMetrics/ios-branch-deep-linking/issues/370, Facebook is now calling openUrl any time from within the app to handle their new auth flow. This incorrectly will force Branch to call the callback block with the same current session parameters.
This change will prevent the callback block from executing if the session is already initialized. @ahmednawar @derrickstaten

Fix for Facebook calling openUrl from within the app

---

Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
Branch.framework/Versions/A/Headers/BranchView.h
Branch.framework/Versions/A/Headers/BranchViewHandler.h

make Branch view header files public in the framework since our umbrella header for building modules imports it

expose branch view header files in framework

---

Branch-SDK/Branch-SDK/BNCServerInterface.m

In response to this issue https://github.com/BranchMetrics/ios-branch-deep-linking/issues/369, we should be trying when the phone is experiencing poor network conditions that make HTTP unreliable. While experimenting, I found that all of these cases return negative HTTP error codes.
@derrickstaten @ahmednawar

Retry in poor network condition

---

Branch-SDK/Branch-SDK/BNCServerInterface.m

One of the partners reported that there were cases that the object returned for key `error` was not a string but another object which led to a crash.
This fix will fallback to the default error string in such case.
@ahmednawar, please review.

Fix for error handling of 400 errors.

---

Branch-SDK/Branch-SDK/BNCServerInterface.m

rename lrtt to brtt cause Branch is a cooler prefix (to avoid confusion with older Android SDK versions with inaccurate round trip times)

brtt instead of lrtt

---

README.md

I believe this is the recommended format per: I believe this is now the recommended format per https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-SDK/Branch-SDK/BranchUniversalObject.h#L54

Switch showShareSheet...andCallback to showShareSheet...completion

---

Branch-SDK/Branch-SDK/BNCServerInterface.m

1. send device information on retries
2. move the startTime variable to the genericHTTPRequest method. This will better computer the brtt on retries as well
@aaustin cc @brian-springer @chanian

better instrumentation

---

Branch.podspec
README.md

Fixes inclusion of Branch and Mopub when using Cocoapods
Relates to #332 
example project with broken include and fix [here](https://dl.dropboxusercontent.com/u/1466870/BranchIO-Mopub-Conflict.zip)

Fix Branch & Mopub Fabric header conflict

---

Branch-SDK/Branch-SDK/BNCCallbacks.h
Branch-SDK/Branch-SDK/BNCContentDiscoveryManager.m
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchUniversalObject.m
Branch-SDK/Branch-SDK/Requests/BranchRegisterViewRequest.m
Branch-SDK/Branch-SDK/Requests/BranchSetIdentityRequest.m
Branch-SDK/Branch-SDK/Requests/BranchSpotlightUrlRequest.m
README.md

This PR adds the proper null/nonnull flags as requested in https://github.com/BranchMetrics/ios-branch-deep-linking/issues/368 @ahmednawar 
This definitely exposed a bit of messiness :(

Nullability and nonnull support for Swift

---

Branch-SDK/Branch-SDK/BranchUniversalObject.m
Branch-TestBed/Branch-TestBed/ViewController.m

add missing $content_type to the BUO data when parsing a dictionary. This was reported in #419 
@aaustin

retrieve content type in BUO

---

Branch-SDK/Branch-SDK/Branch.m

Before this change, it was possible for other requests to be called before init was called. I believe this would cause some types of requests to fail and possibly crash., especially on some of the other platforms like Cordova, where the lifecycle management is quite wonky.

Block other requests until init finished

---

Branch-SDK/Branch-SDK/BNCEncodingUtils.m

This handles the encoding errors I was getting for brtt. The instrumentation dictionary is mutable and this wasn't one of the classes handled in the encoding method.
@aaustin

AIS-40: Brtt encoding

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m

This is in response to https://github.com/BranchMetrics/ios-branch-deep-linking/issues/429. It supports the dictionary based key storage method in the Fabric config.
@derrickstaten

Support separate keys for Fabric config

---

Branch-SDK/Branch-SDK/BranchUniversalObject.h
Branch-SDK/Branch-SDK/BranchUniversalObject.m

This update will:
1. support passing the completion error through the share sheet callback block per the request in https://github.com/BranchMetrics/ios-branch-deep-linking/issues/436
2. fix the nullability label of the activityType as referenced in https://github.com/BranchMetrics/ios-branch-deep-linking/issues/436
@derrickstaten

Pass completion error through

---

Branch-SDK/Branch-SDK/Branch.m

This resolves a potential lifecycle edge case where applicationDidBecomeActive handler is called before the scheduled “callClose” happens (this timer is setup on applicationWillResignActive handler and it is scheduled to happen half a second after). In this case, the SDK will initialize and then be de-initialized when callClose triggers, causing any subsequent call to Branch’s methods will make the application to crash with the error: “Branch SDK Error: making request before init succeeded!".
We've been unable to reproduce this but logically, it is possible.
@derrickstaten

Clear timer on activation

---

Branch-SDK/Branch-SDK/Requests/BranchLoadRewardsRequest.m

We have reports of a rare but unreproducible crash in `loadRewards`. The crash report indicated that there was a `Fatal Exception: NSInvalidArgumentException` on line 51. This pull request adds extensive type checking to ensure arguments are valid.
@agrimn @derrickstaten

Fix unknown credits crash

---

Branch-SDK/Branch-SDK/BranchActivityItemProvider.m

Notes (iOS 9 and 10) also scrapes the link upon sharing similar to Facebook et al. This PR adds it to the list of scraping channels to ignore the first click.
@derrickstaten @aaustin @E-B-Smith

AIS-83 add notes to the list of scraping channels

---

Branch-SDK/Branch-SDK/BNCContentDiscoveryManager.m

Check that the userActivity is a spotlight one *and* from Branch. This should fix the bug mentioned in #464 
@aaustin @E-B-Smith

fix spotlight indexing check

---

Branch-TestBed-iMessage/Branch-TestBed-iMessage.xcodeproj/project.pbxproj

this fixes the build errors in the iMessage test-bed app. We forgot to include the new content discovery src files in the project. The SDK files are added as symbolic links to the original files but XCode can't see newly added files automatically.
@aaustin @E-B-Smith

add missing src files to XCode project

---

Branch-SDK/Branch-SDK/BranchUniversalObject.m
Branch-TestBed/Branch-TestBed/AppDelegate.m

* Suppressed warnings for deprecated push notification types in TestBed
* Fixed crash bug in - (void)userCompletedAction:(NSString *)action (AIS-91)

Fixed userCompletion crash due to nil values.

---

Branch-SDK/Branch-SDK/BNCDeviceInfo.h

Default property attribute 'assign'. NSNumber should be defined using retain or strong to manage it's lifecycle.

Change property attribute to strong

---

Branch-SDK/Branch-SDK/BNCEncodingUtils.m
Branch-SDK/Branch-SDK/BNCServerInterface.m

We are still getting encoding errors for brtt if we are sending GET requests because we don't support encoding dictionaries to query strings.
After a discussion with brian, we decided not to send brtt info in GET requests. Another error comes up because we also send a metadata dictionary in all requests even if it's empty which results in an encoding error as well. This PR changes that to only send metadata if it contains data.
@aaustin @derrickstaten @E-B-Smith

do not send brtt info in GET requests

---

Branch-SDK/Branch-SDK/BNCDeviceInfo.m
Branch-SDK/Branch-SDK/BNCXcode7Support.h
Branch-SDK/Branch-SDK/BNCXcode7Support.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
Branch-TestBed/Branch-TestBed/AppDelegate.m
carthage-files/BranchSDK.xcodeproj/project.pbxproj

I added a dummy category on NSLocale so that iOS 10 code will compile on Xcode 7.
I've confirmed that this patch compiles with both Xcode 7 and Xcode 8.
@aaustin @ahmednawar

Xcode 7 support

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
ChangeLog.md

- Check for older versions of the Fabric SDK instead of just crashing (AIS-102).
- Testing note:  This is a pretty contrived problem that isn't easily testable.
I stepped through the code with the debugger and it worked.

Fabric version fix ais 102

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/BNCServerRequestQueue.m

Follow [Apple's documentation](https://developer.apple.com/reference/objectivec/nsobject/1418639-initialize) and check to make sure the class is the expected class in the `+ (void)initialize` methods. Apple's code listing 1:
``` Objective-c
+ (void)initialize {
if (self == [ClassName self]) {
// ... do the initialization ...
}
}
```

Properly check class on +initialize calls

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/BNCServerRequestQueue.m

In this new file design, we were spitting out a giant error message for preferences and the queue when the first time the SDK was installed. We should not be throwing errors or warnings unless there's a problem. @ahmednawar

Clean up file presence warnings

---

Branch-SDK/Branch-SDK/BNCXcode7Support.h
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/Requests/BranchInstallRequest.m
Branch-SDK/Branch-SDK/Requests/BranchOpenRequest.m
Branch-TestBed/Branch-TestBed/AppDelegate.m

* iAd data is now sent on installs as well as opens.
* Fixed iOS 8 crash bug when 'requestAttributionDetailsWithBlock:' is not present.

* iAd data is now sent on installs as well as opens & crash bug.

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/BNCServerRequestQueue.m
Branch-TestBed/Branch-TestBed/Base.lproj/Main.storyboard
Branch-TestBed/Branch-TestBed/LaunchScreen.storyboard

I made the Branch preference directory path URL more robust.  I added:
1) More checks in code for failure and better recovery.
2) I added _Nonnull for compiler level checking of these code paths.
3) A worst case backup plan if normal Branch prefs directory creation fails.
n.b.: Storyboards were updated so that Xcode 7 could be tested.
Since we don't know the underlying problem this fix may not help but certainly won't hurt.
I tested this code on iOS 7/8/9/10 on iOS devices, and with Xcode 7 and 8.
I tested the worst case option by forcing failure in the normal code path with the debugger.

Robustified the pref file URL creation. inteng-3054.

---

Branch-SDK/Branch-SDK/BNCCallbacks.h

I made the callback params nullable for Swift compatibility.

Updated nullability for Swift.

---

Branch-SDK/Branch-SDK/BNCDeviceInfo.m

When using UIWebView we need to make sure that any JavaScript evaluation
is performed on the main thread, otherwise you risk the potential of
WebKit crashing your app in the background.

Ensure JavaScript is evaluated on main thread

---

Branch-SDK/Branch-SDK/Branch.m

Suggestion comes from https://mobilegrowth.org/discussions/thread/unity-branch-initsession-callback-never-fires-when-deep-linking/
Original notes:
In my [Unity] app, probably due to how scenes are loaded, the Branch.initSession callback never fires when the app is launched from a branch link (handleDeepLink). After lengthy debugging, I found the following patch fixes the issue for me. Is this a legit fix that others might encounter?
See additional thread and testing in https://github.com/BranchMetrics/ios-branch-deep-linking/pull/528

Race condition patch

---

carthage-files/BranchSDK.xcodeproj/project.pbxproj

Included BNCCommerceEvent.h as a public header for Carthage.

Fix Carthage Header #540

---

Branch-SDK/Branch-SDK/Requests/BranchLoadRewardsRequest.m
Branch-SDK/Branch-SDK/Requests/BranchLogoutRequest.m
Branch-SDK/Branch-SDK/Requests/BranchOpenRequest.h
Branch-SDK/Branch-SDK/Requests/BranchRedeemRewardsRequest.m

* This patch will solve some race condition crashes  when the callback is called before it is completely copied.

Make callback block properties atomic/copy.

---

Branch-SDK/Branch-SDK/BNCServerInterface.m
Branch-SDK/Branch-SDK/NSMutableDictionary+Branch.h
Branch-SDK/Branch-SDK/NSMutableDictionary+Branch.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj

This fixes Github issues #551 & #552.
I added a category to NSMutableDictionary that checks if an object is nil before trying to add it to a dictionary, preventing a potential crash.

Safe Dictionary:  Github Issues #551 & #552

---

Branch-TestBed-Swift/README.md
Branch-TestBed-Xcode-7/README.md
Branch-TestBed/README.md

This step is no longer needed because we already redirect to app.link on the backend and we will make app.link the default strong matching domain soon.
cc @E-B-Smith

DOCS-73 - Remove mentions of branch_app_domain

---

Branch-SDK/Branch-SDK/BNCStrongMatchHelper.m

Similar to how UINavigationController and UITabBarController is
currently being handled when adding BNCMatchView. If we don't handle
UISplitViewController this way, BNCMatchViewController will end up in
the split view's viewControllers property which is unexpected and may
lead to crashes later. Split view's viewControllers should only have 1
or 2 view controllers depending on its collapsed / expanded state.
The special handling of UINavigationController and UITabBarController
was added in https://github.com/BranchMetrics/ios-branch-deep-linking/pull/539

Update BNCStrongMatchHelper to handle UISplitViewController

---

Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m

Addition for Appboy support where they can use the `-(BOOL)handleDeepLinkWithNewSession:(NSURL *)url;` method.

handle DeepLink URL with new session - AIS-264

---

Branch-SDK/Branch-SDK/BranchUniversalObject.h

Deprecate Warning added on functions using Share Sheet in BranchUniversalObject - "Use presentActivityViewControllerFromViewController in BranchShareLink". This will give an intuition to the developer about the use of BranchShareLink.

Deprecate warning added in the functions using share sheet in BranchUniversalObject.h

---

Branch-TestBed-Swift/TestBed-Swift.xcodeproj/project.pbxproj
Branch-TestBed-Swift/TestBed-Swift/AppDelegate.swift
Branch-TestBed/Branch-TestBed/AppDelegate.m

Automatic display of deeplink controller is removed and is handled manually in the block of initSession in Appdelegate of obj-c and swift.

automatic display of deeplink controller removed from testbed apps - AIS-127

---

Branch-SDK/Branch-SDK/BNCSystemObserver.h
Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed/Branch-TestBed/ViewController.m

Stop sending the Apple search ad data after attribution has been found or 30 days.

Fix Apple Search Ad Attribution - AIS-267

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.h
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed/Branch-SDK-Tests/BranchSDKFunctionalityTests.m
Branch-TestBed/Branch-SDK-Tests/BranchSDKLoadTests.m
Branch-TestBed/Branch-TestBed/AppDelegate.m

Right now, switching between the `key_test` and the `key_live` confusing.
If the user can set a boolean or explicitly set the key before initialization then switching between live/test is a simple one line code change for the partner.
Options

Make it easier to use the Branch test key - AIS-287

---

Examples/WebViewExample/Podfile
Examples/WebViewExample/README.md
Examples/WebViewExample/WebViewExample.xcodeproj/project.pbxproj
Examples/WebViewExample/WebViewExample.xcodeproj/xcshareddata/xcschemes/WebViewExample-Test.xcscheme
Examples/WebViewExample/WebViewExample/AppDelegate.swift
Examples/WebViewExample/WebViewExample/Info.plist

This illustrates how to select the Branch live or test key without a) making any temporary changes to the code or configuration that later have to be commented or reverted; or b) keeping separate copies of the Info.plist for different configurations. Use the WebViewExample schema for the Branch live environment and the WebViewExample-Test schema for the Branch test environment. This differs a bit from @E-B-Smith's recommendation to use xcconfig files, but amounts to the same thing, I believe. It follows the process outlined [here](https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/docs/branch-environments.md). It may be that an alternate process would be simpler and preferable. However, this is something requested by users at times, and this can be a useful …

Added a WebViewExample-Test schema

---

Branch-SDK/Branch-SDK/BNCDeviceInfo.h
Branch-SDK/Branch-SDK/BNCDeviceInfo.m
Branch-SDK/Branch-SDK/BNCServerInterface.m

This is a bit of a shot in the dark to fix a very rare crash that may involve thread safety.
In stack traces, the crashes never occur until line 301. The deviceInfo.hardwareId and deviceInfo.hardwareIdType are both strings that appear to be safely used above line 301. However, unlike the later properties, these are copied. This doesn't seem a very likely cause, and since the crash has sometimes occurred below line 301, it may just be random to some degree.
With this in mind, I changed every reference property in BNCDeviceInfo to have `copy` semantics rather than `strong` reference semantics. This means that every access to these properties now involves a copy operation. This can improve thread safety, since it means that no two threads can ever handle the same instance of these properties …

BNCDeviceInfo thread safety

---

Branch-SDK/Branch-SDK/BNCCrashlyticsWrapper.h
Branch-SDK/Branch-SDK/BNCCrashlyticsWrapper.m
Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchConstants.h
Branch-SDK/Branch-SDK/BranchConstants.m
Branch-SDK/Branch-SDK/Requests/BranchOpenRequest.m
Branch-TestBed-Swift/TestBed-Swift.xcodeproj/project.pbxproj
Branch-TestBed-Xcode-7/Branch-TestBed.xcodeproj/project.pbxproj
Branch-TestBed-Xcode-7/Branch-TestBed.xcodeproj/xcshareddata/xcschemes/Branch-TestBed.xcscheme
Branch-TestBed-iMessage/Branch-TestBed-iMessage.xcodeproj/project.pbxproj
Branch-TestBed/Branch-SDK-Tests/BNCCrashlyticsWrapper.Test.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj

This change adds several metadata keys to Crashlytics reports if the Crashlytics SDK is linked within the app. The BNCCrashlyticsWrapper method provides a number of methods to accomplish this. They are all no-ops if Crashlytics is not present in the app.
The keys added are:
- **io.branch.sdk.version** The version of the Branch SDK (e.g. "0.16.2").
- **io.branch.device.fingerprintid** The value of `preferenceHelper.deviceFingerprintID`.
- **io.branch.device.lowmemory** Set to YES if a UIApplicationDidReceiveMemoryWarningNotification is received. Absent if no memory warning received.
Including the device fingerprint ID makes it possible, with some effort, to inspect all API traffic associated with a crash in order to help determine the cause. This seems like potentially sensitive …

Crashlytics report enhancement

---

Branch-TestBed-Swift/TestBed-Swift/ViewController.swift

Checking if the link URL returned is nil instead of checking for error. The Branch SDK throws network connectivity error along with the Dynamic link when trying to create a link with the internet connectivity down.

INTENG-3582 Fix to show dynamic links on Swift-Testbed

---

Branch.podspec

Builds with CocoaPods (e.g. WebViewExample) were failing because of the recent networking changes. This change fixes that. It also cleans up the podspec a little to avoid some repetition and modernize a Ruby Hash literal.

Adjust podspec for networking changes

---

Branch-SDK/Branch-SDK/BNCLog.m
Branch-SDK/Branch-SDK/Requests/BranchOpenRequest.m

Added a guard for session data. Sometimes the session data is not stringified (an error on the backend) but this guards against a crash in the SDK.

Add session data guard (GitHub Issue #672).

---

README.md

`getTestInstance` is deprecated in favour of `useTestBranchKey`

Update docs for useTestBranchKey

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/Branch.m
ChangeLog.md

* Logging was calling a protocol method which would lock up initialization sometimes on iOS 8.
* Updated ChangeLog.md.
* Tested on iOS 8 and Xcode 7 and higher.

Initialization would lock up sometimes in iOS 8.

---

Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed/Branch-TestBed/Branch-TestBed-Info.plist

Since we now use certificate pinning to secure our network traffic, Charles Proxy no longer works to debug app network problems.
I've added a way to turn logging on and off via crafted app links.  Using an app link like `myapp://?BranchLogLevel=BNCLogLevelAll` (or a universal link with the same query string) turns on the logging for the app.  The log messages can be read using the Console app or Xcode on a Mac.
Also, per @jdee , I added a way to set the log level in the app's Info.plist file.  Set the `BranchLogLevel` key in the Info.plist to the desired log level string.  The strings are defined in the `BNCLog.h`file.

Added ability to turn logging on and off via links / Info.plist.

---

Branch-SDK/Branch-SDK/Networking/Requests/BranchShortUrlRequest.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchShortUrlSyncRequest.m
Branch-TestBed/Branch-SDK-Tests/BranchShortUrlRequestTests.m
Branch-TestBed/Branch-SDK-Tests/BranchShortUrlSyncRequestTests.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj

This allows for creation of aliases with an `$identity_id` field.
~~Also added a TEST_HOST to TestBed in order to use cmd-U in Xcode.~~ (This wasn't necessary and seems to be responsible for some test failures unrelated to the changes here.)

[INTENG-3725] Remove filter on alias length for identityID

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.h
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchInstallRequest.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchOpenRequest.m

* Send the Apple Search Ad attribution only when it changes.
* Removed some code that has been commented out for a while.

Send the Apple Search Ad attribution only when it changes (DLA-969).

---

Branch-SDK/Branch-SDK/Branch.m

To support old and new API for automatic deeplinking Controller, there are two types of value existed in deepLinkControllers dictionary: BNCDeepLinkViewControllerInstance and UIViewController.
`branchSharingController.deepLinkingCompletionDelegate = self` was set before checking type of the deepLinkControllers' value

Bug fix for automatic deeplinking controller

---

Branch-SDK/Branch-SDK/BranchUniversalObject.h

The `locallyIndex` property is on `BranchUniversalObject`, not `BranchContentMetadata`.

Fix incorrect deprecation message.

---

Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed/Branch-SDK-Tests/BNCTestCase.h

Apple Search Ads weren't timing out on iPad which prevented Branch initialization. I added a 10 second timeout for search ads before initialization continues.

Added Apple Search Ads Time Out

---

Branch-SDK/Branch-SDK/UIViewController+Branch.m

We were seeing a crash on  < iOS 11 along the lines of:
`[AppDelegate window]; unrecognised selector sent to instance`
The `window` var on the UIApplicationDelegate protocol is optional - and for a couple of reasons we don't actually have it in our app delegate.
This PR just wraps the crashing call in `respondsToSelector`
On the devices I tested with this change - the keyWindow was always found on the next attempt:
`keyWindow = [UIApplicationClass sharedApplication].keyWindow;`
I'm unsure why this is not happening on iOS 11 btw

Fix for crash on pre iOS 11 where the application delegate does not have a window variable

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.m

Create the Branch settings directory in a more thread safe way.  This could be a problem on the newer, more thread aggressive iPhones (iPhone X).

Create the Branch directory in a more thread safe way.

---

Branch-SDK/Branch-SDK/BNCPreferenceHelper.h
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/Networking/BNCServerInterface.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchOpenRequest.m
Branch-TestBed/Branch-SDK-Tests/BNCURLBlackList.Test.m
Branch-TestBed/Branch-TestBed-UITests/UITestBed/Info.plist
ChangeLog.md

* Added code that clears the blacklisted URL after sending the regex pattern to the server.
* Removed an old NSLog from debugging.

Fix blacklist open with URI scheme DEVEX-341

---

Branch.podspec

Updated subspec for podspec in order to include `SafariServices` framework with `without-IDFA` subspec for more reliable session matching.

Podspec: Add SafariServices for `without-IDFA` subspec

---

README.md

In Swift example method `application(_:continue:restorationHandler:)` returns always `true` and ignoring Branch response. It's fine in Objective-C example.

Fix inconsistency between Objective-C and Swift example

---

Branch-SDK-Tests/Branch-SDK-Tests/BNCURLBlackList.Test.m
Branch-SDK/Branch-SDK/BNCCommerceEvent.m
Branch-SDK/Branch-SDK/BNCDeviceInfo.m
Branch-SDK/Branch-SDK/BNCFieldDefines.h
Branch-SDK/Branch-SDK/Networking/Requests/BranchOpenRequest.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchUserCompletedActionRequest.m

* Don't send idfa for v2-events when in debug mode.
* Fixed some unit test conditions.

Don't send IDFA when in debug mode. DEVEX-685

---

README.md

Objective-C function was being called with a "swifty" syntax and caused an error in Xcode.
Similar to Issue #855 which was fixed in 6d6a9049e5c5e21ea77aa113d5e449bf1150155f.
PR submitted against `master` branch because it's a docs change.

README: Fix Objective-C function call

---

Branch-SDK/Branch-SDK/Branch+Validator.m

Fixed a crash which occurred when the serverBundleIdentifier returned by the API is NULL
JIRA: [INTENG-4289](https://branch.atlassian.net/browse/INTENG-4289) 
Steps to reproduce:
1. Remove Bundle ID from the Link Settings page on the dashboard 
2. Run the SDK integration validation on the app. Branch.getInstance().validateSDKIntegration()

[INTENG-4289] Fixed crash on validateSDKIntegration()

---

Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-TestBed/Branch-SDK-Unhosted-Tests/Branch_setBranchKeyTests.m
Branch-TestBed/Branch-SDK-Unhosted-Tests/Info.plist
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
Branch-TestBed/Branch-TestBed.xcodeproj/xcshareddata/xcschemes/Branch-SDK-Unhosted-Tests.xcscheme

**Replace NSException with NSError in setBranchKey.**
Remove NSException use. This fixes the crash on misconfiguration.
Add an NSError out parameter. This allows runtime handling of branch initialization errors. Technically, they could have done it with a try catch, but Apple discourages that for typical errors.
Add a method that maintains the old API signature and just prints the error.
Add unit tests to verify changes.  This includes a new unhosted test target to avoid initialization done by our host app.  This test suite must run against simulator.
**Testing**
Check out branch.  Review and run unit tests in the Branch-SDK-Unhosted-Tests suite.

SDK-76 nsexception in setBranchKey

---

Branch-SDK-Tests/BranchEvent.Test.m
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/BranchEvent.h
Branch-SDK/Branch-SDK/BranchEvent.m
Branch-TestBed/Branch-TestBed/ViewController.m

**Changes due to updated spec**
1. Ad type constants are now CAPS  
2. BUO is sent
3. All events are routed through the same logic.  There is no difference between the custom and standard API.  This is how the current implementation works.
**Old description:**
These are new standard events for FB and Tune.  Most of these new standard events do NOT support the BranchUniversalObject.  Only RESERVE supports the BUO.
Also there is a behavior change.  Previously standard events created via the customEvent API would go to the standard server endpoint.  Now all events created via the customEvent API will go to the custom server endpoint.
All events created via BranchUniversalObject's userCompletedAction are treated as custom events.

DEVEX-875 add new standard events

---

Branch-SDK/Branch-SDK/BNCKeyChain.m

Same effect as previous setting, but disallows being restored (from backup) to a _different_ device.
More secure this way.
When adding these items to the Keychain, the App does not explicitly exclude the items from device backups, which will allow sensitive data to get exported to iTunes and iCloud backups.
Having sensitive data sent to iCloud exposes it to both Apple, Inc. and an attacker with the ability to compromise the user's iCloud account (similarly to the iCloud celebrity hack, described in http://en.wikipedia.org/wiki/August2014celebrityphotoleaks/).
Additionally, exporting data to iTunes backups allows an attacker with physical access to the device and its passcode to use the iTunes encrypted backup functionality to extract all the Keychain items (that are flagged for backups) …

Update BNCKeyChain kSecAttrAccessible value

---

Branch-SDK/Branch-SDK/Branch.m

Branch now calls the callback when a non-branch URI scheme is called from the foreground.  This is more consistent behavior with android and universal links.
To test, from within a test app call a scheme with no parameters, the branch callback should be called with +non_branch_link and the calling scheme.

Inteng 4827 handle non branch links properly

---

Branch-SDK/Branch-SDK/BNCTuneUtility.m

Silly error.  Missed cause the flag only matters on first install.  But for consistency lets fix this.

SDK-594 fix tune data check only works once

---

Branch-TestBed-Swift/TestBed-Swift.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings

Source integration of Carthage requires the swift project to build successfully.  Forgot to commit the project settings with the switch to the new build system.
Binary integration works without this change.

SDK-603 use new build system in swift test project

---

Branch-SDK-Tests/BNCPreferenceHelperTests.m
Branch-SDK/Branch-SDK/BNCPreferenceHelper.h
Branch-SDK/Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch-SDK/BNCURLBlackList.m

Example usage:
`[BNCPreferenceHelper preferenceHelper].branchBlacklistURL = @"https://example.com";`
This must be before Branch init.

SDK-605 add optional config to set the blacklist url

---

Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchLastAttributedTouchData.h
Branch-SDK/Branch-SDK/BranchLastAttributedTouchData.m
Branch-SDK/Branch-SDK/Networking/BNCServerInterface.m
Branch-SDK/Branch-SDK/Networking/Requests/BranchLATDRequest.h
Branch-SDK/Branch-SDK/Networking/Requests/BranchLATDRequest.m

Allow attribution window.  
Apparently the server will handle 0, so allow that through.  Block negative numbers and any value greater than a year.

SDK-614 LATD correction

---

Branch-SDK-Tests/BNCAppleAdClientTests.m
Branch-SDK-Tests/BNCAppleSearchAdsTests.m
Branch-SDK/Branch-SDK/BNCAppleAdClient.h
Branch-SDK/Branch-SDK/BNCAppleAdClient.m
Branch-SDK/Branch-SDK/BNCAppleReceipt.m
Branch-SDK/Branch-SDK/BNCAppleSearchAds.h
Branch-SDK/Branch-SDK/BNCAppleSearchAds.m
Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchCrossPlatformID.h
Branch-SDK/Branch-SDK/BranchLastAttributedTouchData.h
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
Branch-TestBed/Branch-TestBed/AppDelegate.m
Branch-TestBed/Branch-TestBed/Branch-TestBed-Prefix.pch

See ticket for background information on this design. 
1.  Used the same delay for first and every retry.  Which is different from spec.
2.  No public API to modify behavior, negotiating with Product on that.
3.  Missing end to end tests around delay, retry and time outs.

SDK-513 search ads update

---

Branch-SDK/Branch-SDK/BNCCommerceEvent.m
Branch-SDK/Branch-SDK/Branch.m

Blind fix attempt for a rare crash I'm not able to repro.
1.  Typo in serialization for commerce event.
2.  Queue priorities are now set to default.

SDK-450 rare serialization issue

---

Branch-SDK/Branch-SDK/BNCAppleReceipt.h
Branch-SDK/Branch-SDK/BNCUserAgentCollector.h
Branch-SDK/Branch-SDK/BNCUserAgentCollector.m
Branch-SDK/Branch-SDK/NSError+Branch.h

C++ does not enable modules by default.  Add fallbacks to support it.

SDK-667 add fallback for no modules

---

Branch-SDK/Branch-SDK/BranchEvent.h
Branch-SDK/Branch-SDK/BranchEvent.m

The contentItems and customData properties of BranchEvent are unnecessarily using mutable collection objects, rather than immutable ones.
Casting a NSDictionary to NSMutableDictionary does not actually make it a mutable dictionary. It just makes the compiler *think* that it is mutable, allowing the developer to call a method that only applies to mutable collections on an immutable one, which causes a crash.

improve BranchEvent's contentItems and customData properties

---

Branch-SDK/Branch-SDK/Branch.h
Branch-SDK/Branch-SDK/Branch.m
Branch-SDK/Branch-SDK/BranchEvent.m

Found while researching INTENG-7730
Calling logEvent before init can complete leads to inconsistent behavior.  This could result in a deferred deeplink arriving late.

SDK-713 fix log event error

---

Branch-SDK-Tests/BNCDeviceInfoTests.m
Branch-SDK/Branch-SDK/BNCDeviceInfo.h
Branch-SDK/Branch-SDK/BNCDeviceInfo.m

Server release today broke the iOS SDK 0.31.x series.  Fixing it on the client side first.

SDK-717 convert cpu type to a string

---

Branch-SDK/Branch-SDK/BNCThreads.h

A fix for the implicit conversion warnings (https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/995)

Fix implicit conversion warnings (#995)

---

Branch-SDK/Branch-SDK/BNCEncodingUtils.h
Branch-SDK/Branch-SDK/BNCEncodingUtils.m
Branch-SDK/Branch-SDK/BNCLinkData.m
Branch-SDK/Branch-SDK/BranchContentDiscoverer.m

Used an MD5 to create keys for an object cache, this triggers security scanners.  Replace this code.

SDK-422 object cache improvement

---

Branch.podspec

The project's LICENSE.txt declares an MIT licence, but this was not reflected in the podspec, which indicated a "Proprietary" licence.

Correct Podspec licence declaration to MIT

---

Branch.podspec

Close #1012 #999
If our library was installed via CocoaPods, Xcode 11.4 will issue the warning "MobileCoreServices has been renamed. Use CoreServices instead.".
How to fix: Do not explicitly link `MobileCoreServices.framework` in the CocoaPods generated project, by deleting `MobileCoreServices` from the `spec.frameworks` attribute in our podspec file.
More info: https://github.com/AFNetworking/AFNetworking/pull/4532

Fix warning: MobileCoreServices has been renamed. Use CoreServices instead.

---

Branch.podspec

Updating the repo URL in the podspec to the current URL, instead of an old one requiring a redirect.
Also updated the homepage element to point to the docs. I've been doing that elsewhere: web, RN, C++.
~~Still need to test this.~~ Works when testing from my local copy with `pod 'Branch', path: '...'`.

[SDK-992] Update repo URL and homepage in podspec

---

Branch-TestBed/Branch-SDK-Tests/BNCServerInterface.Test.m

Added a unit test for the `X-Branch-Request-Id` => `[BNCServerResponse requestId]` mapping.

[SDK-1076] Add a unit test for Request ID mapping

---

Branch-SDK/BNCPreferenceHelper.h
Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/BNCServerInterface.m

A fix for the issue described in https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/918
We are using Branch in a large application and get a small handful of crashes in `[BNCEncodingUtils sanitizedStringFromString:]`
I looked through the code and I believe I have found a potential source to the problem. In `prepareParamDict`, the NSMutableDictionary `instrumentationDictionary` is returned without making a copy. Given the `@synchronized` code around access to this dictionary, it is likely to be updated by multiple queues at once.
The correct fix is to create a new method which makes a copy of this dictionary _while still within the @synchronized lock`!

Fix intermittent crash in `sanitizedStringFromString`

---

Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/BNCServerRequestQueue.m
Branch-TestBed/Branch-SDK-Tests/BNCUserAgentCollectorTests.m

Removes a couple very old data copy methods when upgrading from SDK version 0.12.13.

SDK-1106 remove initialize use

---

Branch-SDK/BNCSKAdNetwork.m
Branch-SDK/Branch.h
Branch-TestBed/Branch-SDK-Tests/BNCSKAdNetworkTests.m

Reduce the default timeout to 24 hours.

CORE-1711 reduce default SKAdNetwork timeout from 72 hours to 24 hours

---

Branch-SDK/BNCPreferenceHelper.h
Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/Branch.h
Branch-SDK/Branch.m

Renamed the API for better readability in Swift.
Also added a safety check that only allows calling the method once, since the ATT prompt can only be shown once.  This limits the impact of an erroneous implementation from sending a lot of opt_in or opt_out events.

CORE-1768 rename api for better readability, add safety check

---

Branch-SDK/BNCSystemObserver.m

We're seeing reports that the call to the Apple Attribution token api can hang.
Added a 100ms timeout to the Apple Attribution token call.

CORE-1893 add timeout to apple attribution token

---

Branch-SDK/BNCApplication.h
Branch-SDK/BNCApplication.m
Branch-SDK/BNCKeyChain.h
Branch-SDK/BNCKeyChain.m
Branch-SDK/BNCServerRequestQueue.h
Branch-SDK/BNCServerRequestQueue.m
Branch-TestBed/Branch-SDK-Tests/BNCApplication.Test.m
Branch-TestBed/Branch-SDK-Tests/BNCKeyChain.Test.m
Branch-TestBed/Branch-SDK-Tests/BNCServerRequestQueueOldTests.m
Branch-TestBed/Branch-SDK-Tests/BNCServerRequestQueueTests.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj

Since we added support for secure coding on newer versions of iOS, we found archiving on Keychain and the network queue was failing due to mismatched types. This PR fixes both those issues.
For keychain, we only store NSDate. The code has been updated to always expect NSDate.
For the network queue, there was a refactor to improve testability around archive and unarchive of the network queue. The main change is that we only allow some classes to be archived and retrieved.  For older versions of iOS and the SDK, we filter on archive and retrieval.

CORE-1916 fix keychain and queue

---

Branch-SDK/BranchShareLink.h
Branch-SDK/BranchShareLink.m
Branch-SDK/BranchUniversalObject.h
Branch-SDK/BranchUniversalObject.m
Branch-TestBed/Branch-TestBed/ViewController.m

→ Added property *lpMetaData in BranchShareLink.
→ BranchShareLink class now conforms to UIActivityItemSource protocol
→ Removed getBranchActivityItemWithLinkProperties function from BranchUniversalObject class.
→ Updated function showShareSheetWithShareText to call BranchShareLink functions.

Core 1589 share sheet configuration

---

Branch-SDK/BNCTelephony.m

Fixed warning for deprecated method - subscriberCellularProvider.

Core 1577 remove deprecated methods

---

.github/custom-scripts/create-release.js

This actually wasn't working anyway. It was producing full releases, as if `prerelease: false` had been specified. I manually changed the `1.4.0-test.1` release to prerelease afterward.
This flag can be exposed in a later iteration. For now, this workflow should produce full releases.
@BranchMetrics/core-team

[SDK-1131] Remove prerelease flag.

---

.github/workflows/release.yml
fastlane/.gitignore
fastlane/Fastfile
fastlane/lib/helper/cocoapods_helper.rb

The release.yml workflow doesn't take any parameters. During testing, I was supplying a `tag` parameter, but this doesn't need to be exposed here in the current workflow. This change ensures that whatever is in the podspec is used for the tag. The arrangement of these steps can be changed. For now, keeping version bump and release separate manual steps.
@BranchMetrics/core-team

Use CocoaPods to get the current version from the podspec.

---

.github/custom-scripts/create-release.js

This will create a release with a note reading `[Insert ChangeLog update]`. This will be manually done by the maintainer after each release, having update the ChangeLog.txt manually (via PR) before the release.
We can also scoop the manual ChangeLog update out of the file, but the formatting will probably need attention.
The placeholder can be anything, including blank.

[SDK-1133] Remove generated release note

---

Branch-SDK/Branch.m

Replaced warning suppression with @available check. Only one instance was found.

[SDK-404] Replaced warning suppression with version check.

---

Branch-SDK/BranchPluginSupport.m

App no longer crashes when trying to call deviceDescription() in Swift.

[SDK-1345] Added .stringValue to NSNumber in BranchPluginSupport.deviceDescription()

---

Branch-SDK/BranchShareLink.m

Changed the placeholder URL in the Share Sheet from a long URL with bnc.lt, to a short URL with the app's app.link url.

[SDK-1168] Fixed bnc.lt from appearing in the Share Sheet

---

Branch-SDK/Branch.h
Branch-SDK/Branch.m
Branch-SDK/BranchShareLink.m

Created a method that returns a long URL with app.link. This is used to properly show the app.link URL, link title, and link image in the Share Sheet preview
It fetches the user's app.link from preferenceHelper.userUrl, then shortens it to just the *.app.link. If one isn't available, then the usual bnc.lt long URL is generated like before.

[SDK-1168] Added getLongAppLinkURLWithParams()

---

Branch-SDK/BNCPreferenceHelper.m

Xcode will warn when NSNumber is not explicitly in the serialize list, even though it will serialize just fine.

SDK-1199 add NSNumber 

---

Branch.podspec

https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/pull/1122 added the dependence on `LinkPresentation`. This adds it so `weak_framework` since it's only available in iOS 13.0 and up.

Add missing `LinkPresentation` dep to podspec

---

Branch-SDK/BNCPreferenceHelper.m
Branch-SDK/BNCServerInterface.m

- Adds the `developer_identity field` to v1/open requests under the `identity` parameter. Also clears `developer_identity` when logging out or disabling tracking.
https://branch.atlassian.net/browse/SDK-1528

[SDK-1528] Add developer_identity to v1/open requests

---

.github/ISSUE_TEMPLATE
.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.yml
SECURITY.md

SDK-1614 -- Github Issue Template for SDK repos
Introduces the new issue report form - references https://github.com/BranchMetrics/web-branch-deep-linking-attribution/issues/new/choose
The issues we've had raised have been inconsistent quality and often lack important details to resolve, necessitating more clarification leading to increased latency. This form requires and encourages issues to have more details. 
- [✅] Bug fix (non-breaking change which fixes an issue)
Preview file in PR, spot any typos or mis-references to other repos/improper values.

New issue report form

---

Branch-SDK/BranchPluginSupport.m

SDK-1625
INTENG-15831
Updated BranchPluginSupport to safely use BNCDeviceInfo. This mirrors the code within BNCDeviceInfo itself.
Reports of a rare crash in this area code when using Adobe Launch iOS.
The crash is fairly rare, the only reliable repro we've seen is using AdobeLaunch iOS on a real device running an older version of iOS. We suspect this is due to a threading issue where BNCDeviceInfo is being mutated from multiple threads.

SDK-1625 Protect BNCDeviceInfo

---

Branch.podspec
ChangeLog.md
Package.swift
carthage-files/BranchSDK.xcodeproj/project.pbxproj
carthage-files/checksum.txt
carthage-files/checksum_noidfa.txt
carthage-files/checksum_static.txt
carthage-files/checksum_static_noidfa.txt

SDK-1664 release
The new pasteboard code requires Xcode 14+
Xcode 14 ups the min version to iOS 11 and tvOS 11.
[] podspec min is 11
[] SPM min is 11
[] Branch.a fat binary build no longer looks for i386 and armv7

SDK-1664 update min iOS and tvOS versions to 11

---

Branch-SDK/BranchEvent.m
Branch-SDK/BranchOpenRequest.m

https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/1212 
Updated classes BranchOpenRequest and BranchEvent to remove calls to callback from completion handler of updatePostbackConversionValue. If there is any SKAN error, it will be logged only.
Fix for bug GH-Issue-1212  
- [ X] Bug fix (non-breaking change which fixes an issue)
Test with an app which -
* Has SKAN Enabled.
* Calls following function with non-nil callback `- (void)initSessionWithLaunchOptions:(NSDictionary *)options andRegisterDeepLinkHandlerUsingBranchUniversalObject:(callbackWithBranchUniversalObject)callback ` 
* If SKAN fails and returns some error, above function should not fail.

GH-Issue-1212 Fix - Removed calls to callback from completion handler of updatePostbackConversionValue.

---

Branch-SDK/Branch.h
Branch-SDK/Branch.m

SDK - 1671 [iOS] Mark v1/event methods as deprecated  
Marked 'sendCommerceEvent' ans 'userCompletedAction' methods as deprecated. Added runtime warning messages using NSLog also when these methods are used
Remove v1/event method calls
* Compile TestBed App and check Build logs for deprecated methods warning.
* In Test bed, press buttons - 'Send Complex Event' and 'Send Commerce Event' and see if warning methods are printed.
* Check if logs are printed even if SDK logging is not enabled.

Sdk 1671 - mark v1event methods deprecated

---

.github/workflows/integration-tests.yml
.github/workflows/release.yml
.github/workflows/verify.yml
.github/workflows/version-bump.yml

Auto-generated GHA actions upgrade ios-branch-deep-linking-attribution. Need to upgrade actions, because of Node v.12 is deprecated (https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) and set-output and save-state commands are deprecated  (https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

INFRA-XX Auto-update GHA actions

---

Branch-SDK/BNCPartnerParameters.h
Branch-SDK/BNCPartnerParameters.m
Branch-SDK/Branch.h
Branch-SDK/Branch.m
Branch-TestBed/Branch-SDK-Tests/BNCPartnerParametersTests.m

SDK-1437 Snap partner parameter support
Some clients wish to attach hashed Snap partner parameters to Branch events. 
There is a new API for adding Snap partner parameters, `addSnapPartnerParameter`. Once set, the parameter will be included in future Branch events. Note the value must look like a valid hash, or the Branch SDK will silently drop it.

SDK-1437 snap partner parameters

---

BranchSDK/BNCNetworkService.m

SDK-1663 revert thead queue priority change
Thread queue is returned to NSQualityOfServiceUserInteractive. This is cause the BUO showShareSheet is a UI call and needs to be a higher priority.
Avoid potential thread priority inversion.
This is a reversion to previous behavior, however you can test by calling the BUO showShareSheet and verifying that Xcode does not flag the code.

SDK-1663 revert thread queue change.

---

BranchSDK.podspec
BranchSDK/BNCConfig.m
ChangeLog.md

SDK-1613 prep 2.0.0 release
Increase version to 2.0.0
Update changelog
Remove iAd from cocoapods as it's slated to be deprecated by Apple

SDK-1613 update version to 2.0.0. Update changelog

---

BranchSDK/BranchEvent.m
BranchSDK/BranchOpenRequest.m

SDK-1802 fix warning on tvOS
We marked the method used to call SKAdnetwork as iOS 16.1+ which is causing warnings on tvOS. First tvOS does not support SKAdnetwork, second our method calls SKAdnetwork via selectors so it will do nothing on tvOS anyways.
Warnings fix
When integrating with a tvOS app you should not see warnings

SDK-1802 fix warning on tvOS.

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
BranchSDK/BNCConfig.m
ChangeLog.md
scripts/version.sh

SDK-1838 prep iOS 2.1.0 release
Update changelog
```
Branch iOS SDK 2.1.0 contains improvements to testing and plugin support (Unity, RN, etc). Most clients will see no change. 
- SDK-1831 - Improved branch.json support
* Support for logging via `enableLogging`.
* Removed old Apple Search Ads support.
* Support for deferred SDK initialization. This allows improved plugin lifecycle support.
- SDK-1802 - Fix tvOS warnings.
- SDK-1774 - Update Branch TestBed UI.
```
Update version to 2.1.0
Just updates the changelog and versions.

SDK-1838 prep iOS 2.1.0 release

---

BranchSDK/BNCSKAdNetwork.m
BranchSDK/BNCSystemObserver.m

SDK-1747 macCatalyst SKAN issue
Although we do not officially support macCatalyst yet, we want to be as compatible as possible with it. This fixes an issue where the SKAN if available check did not include macCatalyst.
Fix potential crash on macCatalyst when running on macOS 13.0
Use on a catalyst app on macOS 13.0
Invoke the skAdNetworkUpdatePostbackConversionValueCoarseValueLockWindow call

SDK-1747 macCatalyst SKAN issue

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
BranchSDK/BNCConfig.m
ChangeLog.md
scripts/version.sh

- SDK-1800 - Extract GBRAID & GCLID from Branch referred uri/url
* Added new class to parse valid query parameters from URLs and append them to requests.
- SDK-1747 - Added if available check for SKAN on Mac Catalyst

Release 2.1.1

---

BranchSDK/BNCReferringURLUtility.m

Small change removing unnecessary line, which also caused a warning.

Removed unnecessary line causing warning

---

BranchSDK/BNCLog.m
BranchSDK/BNCPreferenceHelper.m
BranchSDK/NSError+Branch.m
BranchSDK/NSString+Branch.m
BranchSDK/UIViewController+Branch.m

SDK-1908 Xcode 14.3 fix warnings about c functions with empty argument lists
K&R pages 72-73. 
"Furthermore, if a function declaration does not include arguments, as in
`double atof();`
that too is taken to mean that nothing is to be assumed about the arguments of atof; all parameter checking is turned off. This special meaning of the empty argument list is intended to permit older C programs to compile with new compilers. But it's a bad idea to use it with new programs. If the function takes arguments, declare them; if it takes no arguments, use void."
Xcode is finally warning on it, and we shouldn't have written it that way in the first place.
Fix warnings
On Xcode 14.3 build an app with the released version of BranchSDK and you'll see warnings about empty C functions.
Rebuild with this …

SDK-1908 Xcode 14.3 fix warnings about c functions missing void

---

SDKIntegrationTestApps/PostRelease-tvOSReleaseTest-Cocoapods/tvOSReleaseTestTests/tvOSReleaseTestTests.swift
SDKIntegrationTestApps/tvOSReleaseTest-Cocoapods/tvOSReleaseTestTests/tvOSReleaseTestTests.swift
SDKIntegrationTestApps/tvOSReleaseTest-Manual/tvOSReleaseTestTests/tvOSReleaseTestTests.swift

SDK-1964 -- iOS SDK GHAs sometimes waits indefinitely for tvOS simulators.
https://branch.atlassian.net/browse/SDK-1964
Changed disable tracking to false. True was making integration tests to hang on GH runners for tvOS. Though its working fine locally. 
Run GHA "Pre Release SDK Integration Tests". It should finish tests execution in  15-20 minutes
For fake/empty commits use following command - 
git commit --allow-empty -m "Trigger Build for testing"

Fix for GHA time out issue on tvOS 

---

Branch-TestBed/Branch-SDK-Tests/BNCPasteboardTests.m
Branch-TestBed/Branch-SDK-Tests/BNCSKAdNetworkTests.m
Branch-TestBed/Branch-SDK-Tests/BranchShareLinkTests.m
Branch-TestBed/Branch-TestBed/PasteControlViewController.m
Branch-TestBed/Branch-TestBed/ViewController.m
BranchSDK/BNCServerInterface.m
BranchSDK/BNCSystemObserver.m
BranchSDK/Branch.m
BranchSDK/BranchEvent.m
BranchSDK/BranchInstallRequest.m
BranchSDK/BranchOpenRequest.m
BranchSDK/BranchShareLink.m
ChangeLog.md

Adds macCatalyst guards for availability checks that are at or above 13.0 (version Catalyst was introduced in).
We use Branch in a Catalyst app, and we've had crashes before when using APIs that are not properly guarded, forcing us to do a fork and make the changes in our copy of Branch.

Adds macCatalyst guards for missing availability checks

---

.github/workflows/dependabot-merger.yml

SDK-2032 -- Dependabot - Get caught up on dependabot PRs
Created a new GHA that automatically takes the open dependabot PRs, and merge them into a separate for testing all at once. 
This will make it much easier to manage dependabot PR's by being able to easily test multiple of them at once. 
Manually run the GHA and check the new dependabot-test-branch.

[SDK-2032] Create dependabot-merger.yml

---

.github/workflows/dependabot-merger.yml

N/A
This PR fixes an overly permissive grep that would allow an attacker to automatically merge PRs by impersonating dependabot. This PR and fix will be pulled into the new dependabot testing branch automatically by the vuln it's fixing. The new filter strictly enforces that `app/dependabot` is the PR author.
Landing unreviewed potentially hostile code is dangerous.
This was tested by first creating a PR on a branch containing the word "dependabot". Manually running the filter command
in the original workflow confirmed that the PR would be automerged as part of a dependabot automerge.
Vulnerable filter: https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/blob/75381d35f8a36eae2ecd2160d65bf3f3a674ce9e/.github/workflows/dependabot-merger.yml#L37C1-L37C11
Testing PR: …

fixed incorrect automatic merge filter

---

BranchSDK/Branch.m

SDK-1997 -- Update share sheet methods to still create a short link when tracking is disabled
Update the share sheet methods to still generate short links when tracking is disabled instead of long links. By removing the initialization status check, the SDK will make a `v1/url` call instead of constructing a long link.
Currently, `getShortUrl()` already can be used to create a short link when tracking is disabled, but the share sheet methods would still create a long link. This brings parity between the two and overall improves the share sheet behavior.
Trying to share a link via the share sheet and using BranchShareLink while tracking is disabled and enabled.

[SDK-1997] Update share sheet to use short links with tracking is disabled

---

BranchSDK/BNCCallbacks.h

SDK-2084 -- Create new callback for NSData in BNCCallbacks
A new callback, `callbackWithData`, has been added to BNCCallbacks to support QR codes in Unity. 
For the Unity SDK to use the QR code methods, a new callback with NSData is required. The changes have already been made one the Unity side, so now the iOS SDK just needs to be updated so it can be referenced. 
Confirm there were no unintended changes from this.

[SDK-2084] Create new callback for NSData in BNCCallbacks

---

.github/workflows/sync-readme-changelog.yml
.github/workflows/update-readme-changelog.yml

SDK-2072 -- Help Docs automate Readme changelogs
Created a GitHub action that runs whenever a release is created. It takes the release name and description, then updates the public docs version history at https://help.branch.io/developers-hub/docs/ios-version-history.
Lastly, the action sends a slack message in the #sdk channel to broadcast the new release.
To streamline and speed up the release process even more while keeping out docs up to date.

[SDK-2072] Automatically sync Readme docs version history page

---

.github/workflows/automation-trigger-test.yml

SDK-iOS build response key changes
Changing APP_URL to BrowserStackIOSNewBuildKey
The automation branch points to UpdateBrowserStackEnvVariable

Update iOS build browserStack env variable name

---

.github/workflows/automation-trigger-test.yml

Removed ref to branch "UpdateBrowserStackEnvVariable" in GHA for appium automation.
Previous [pull request](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/pull/1313) was from an old branch so during merging to master it didnt pick up the line where code was deleted.
Check all appium tests are passed and verify from GHA logs, source code was checked out from master branch.

Remove ref to branch "UpdateBrowserStackEnvVariable" in GHA

---

Branch-TestBed/Branch-SDK-Tests/BNCPreferenceHelperTests.m
Branch-TestBed/Branch-SDK-Tests/BNCServerInterface.Test.m
Branch-TestBed/Branch-SDK-Tests/BranchDelegate.Test.m
Branch-TestBed/Branch-TestBed/Branch-TestBed-Info.plist
DeepLinkDemo/Podfile
DeepLinkDemo/Podfile.lock

SDK-2097 -- iOS Test coverage 
Added tests to ensure prefhelper values are being properly set and retrieved. Also updated the testbed's Branch Key.
Increase the iOS SDK's test coverage.
Run the tests and confirm the succeed locally and on GHA.

[SDK-2097] Added Prefhelper tests

---

BranchSDK/PrivacyInfo.xcprivacy
Framework/PrivacyInfo.xcprivacy

SDK-2141 update privacy manifest with EU domain
Add the EU domain to the privacy manifest.
Remove "https://" from the entry as the examples don't include it. This did not appear to cause issues, but we should be consistent with Apple's documentation.
Add the EU domain to the privacy manifest

SDK-2141 update privacy manifest with EU domain

---

Branch-TestBed/Branch-SDK-Tests/BranchUniversalObject.Test.m
BranchSDK/BranchShareLink.h
BranchSDK/BranchShareLink.m
BranchSDK/BranchUniversalObject.h
BranchSDK/BranchUniversalObject.m

SDK-2051 remove Objective-C APIs that confuse Xcode's Swift compatibility
NSError's within callback blocks are converted to exceptions in Swift. This causes unusual behavior when two methods differ only by a NSError in the callback. 
Removed problem public APIs, also added an NSError to one version that did not have one. This is a public API change.
Improve usability for Swift developers.
Attempt to use these APIs in a Swift app, the NSErrors should be converted to exceptions correctly.

SDK 2051 remove api variations that confuse swift

---

Branch-TestBed/Branch-TestBed/Branch-TestBed-Info.plist
BranchSDK/Branch.m

INTENG-19489 fix organic warm open
SDK init status was cleared by the close call, with it's removal we need to clear it elsewhere to maintain previous behavior.
Restore previous behavior around organic opens.
1. Run a test app with the debugger attached.
2. See install or open on app run.
3. Background the app.
4. Foreground the app. Notice no network call to init.
Repeat with this change, and step 4 will have a network call to init.

the SDK state clear happened with the old close call

---

Branch-TestBed/Branch-SDK-Tests/BNCAPIServerTest.m
Branch-TestBed/Branch-SDK-Tests/BNCPreferenceHelperTests.m
Branch-TestBed/Branch-TestBed/AppDelegate.m
BranchSDK/BNCPreferenceHelper.h
BranchSDK/BNCPreferenceHelper.m
BranchSDK/BNCServerAPI.h
BranchSDK/BNCServerAPI.m
BranchSDK/Branch.h
BranchSDK/Branch.m
BranchSDK/BranchPluginSupport.h
BranchSDK/BranchPluginSupport.m

SDK-2118 -- Added a method to set API URL
Added a new method to the Branch class for setting the API base URL to a custom value. This also includes adding a check to the `getBaseURL` method to check for a custom URL. 
To allow clients to provide custom API URLs and gain parity with our Android SDK.
Call the `setAPIURL` method in the AppDelegate and observe the change.
```
Branch *branch = [Branch getInstance];
[branch setAPIUrl:@"https://api2.branch.io"];
```

[SDK-2118] Added a method to set API URL

---

Branch-TestBed/Branch-SDK-Tests/BNCRequestFactoryTests.m
Sources/BranchSDK/BNCRequestFactory.m
Sources/BranchSDK/BNCServerRequestQueue.m
Sources/BranchSDK/Branch.m
Sources/BranchSDK/BranchInstallRequest.m
Sources/BranchSDK/BranchOpenRequest.m
Sources/BranchSDK/Private/BNCRequestFactory.h
Sources/BranchSDK/Private/BranchOpenRequest.h
Sources/BranchSDK/Public/BNCServerRequestQueue.h
Sources/BranchSDK/Public/Branch.h

INTENG-19264 and INTENG-19577
Although the two issues are not the same, they are in related area of code and therefore handled in a single fix PR.
INTENG-19264
On cold link open, there are two iOS lifecycle events in a very small window of time. Our existing code improperly attempts to reconcile the two events, with a potential loss of link data. The frequency of failure depends on how much time is elapsed between the first and second lifecycle calls, a ~0.15s delay repros about 1/10 on our test app. Shorter and longer delays did not repro the issue.
Initial fix is to no longer attempt to reconcile the two close lifecycle events. This means all clients will see two callbacks on cold link open. The first is for the app initialization which will contain no link data, the second is for link …

INTENG-19264 and INTENG-19577 bug fixes

---

Branch-TestBed/Branch-SDK-Tests/NSMutableDictionaryBranchTests.m
Sources/BranchSDK/NSMutableDictionary+Branch.m

SDK-2250
Swap unused string check from `doubleValue` to `boolValue`
Be consistent with the code it is intended to replace.
Unit test has been updated. Note this utility code isn't actually used by the SDK. 

The original code used boolValue

---

Sources/BranchSDK/Branch.m
Sources/BranchSDK/BranchJsonConfig.m
Sources/BranchSDK/Private/BranchJsonConfig.h

SDK-2328 -- Support setting Branch API URL in Branch.json
Added a new field to branch.json for setting the Branch API URL. The config check and setAPIUrl call are done in Branch.m's `initWithInterface()` in the same place as the `deferInitForPluginRuntime()` and `enableLogging()` checks.
To support setting the API URL in our plugins like React Native.
Add `"apiUrl": "https://api.branch.io"` to a branch.json file and observe the API URL properly change for each request.

[SDK-2328] Added API URL check for Branch.json

---

BranchSDK.podspec

SDK-2314
Fix cocoapods privacy manifest to avoid name collisions with other SDKs and the App.
Bug fix
Include this branch via cocoapods and generate a privacy manifest. Notice things are properly put into a bundle.

Fix cocoapods handling of privacy manifests to avoid collision

---

Sources/BranchSDK/BNCContentDiscoveryManager.m
Sources/BranchSDK/BNCSpotlightService.m
Sources/BranchSDK/BNCUserAgentCollector.m
Sources/BranchSDK/BranchActivityItemProvider.m
Sources/BranchSDK/BranchCSSearchableItemAttributeSet.m
Sources/BranchSDK/BranchPasteControl.m
Sources/BranchSDK/BranchShareLink.m
Sources/BranchSDK/Private/BNCContentDiscoveryManager.h
Sources/BranchSDK/Private/BNCSpotlightService.h
Sources/BranchSDK/Private/BNCUserAgentCollector.h
Sources/BranchSDK/Public/BranchActivityItemProvider.h
Sources/BranchSDK/Public/BranchCSSearchableItemAttributeSet.h
Sources/BranchSDK/Public/BranchPasteControl.h
Sources/BranchSDK/Public/BranchShareLink.h

SDK-1217 workaround tvOS SPM issue
Added preprocessor guards on all files that are not valid on tvOS. With other integration methods we can conditionally exclude these files, but it seems SPM does not allow this.
Allow tvOS builds using SPM.
Integrate Branch SDK into a tvOS app using SPM.
App should build properly.

SDK-1217 workaround tvOS SPM issue

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
ChangeLog.md
Sources/BranchSDK/BNCConfig.m
scripts/version.sh

SDK-2372
Fix for tvOS builds when using SPM
SDK builds when tvOS apps are integrated via SPM

SDK-2372 prep iOS 3.4.2 release 

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
ChangeLog.md
Sources/BranchSDK/BNCConfig.m
Sources/BranchSDK/Branch.m
scripts/version.sh

SDK-2387
Revert a change in 3.3.0 to `handlePushNotification`
Fix background push notifications when an app is integrated using the `handlePushNotification` method

Fix issue with handlePushNotification

---

Branch-TestBed/Branch-SDK-Tests/BNCEncodingUtilsTests.m
Sources/BranchSDK/BNCAppGroupsData.m
Sources/BranchSDK/BNCAppleReceipt.m
Sources/BranchSDK/BNCCallbackMap.m
Sources/BranchSDK/BNCDeviceInfo.m
Sources/BranchSDK/BNCEncodingUtils.m
Sources/BranchSDK/BNCEventUtils.m
Sources/BranchSDK/BNCKeyChain.m
Sources/BranchSDK/BNCPartnerParameters.m
Sources/BranchSDK/BNCPasteboard.m
Sources/BranchSDK/BNCPreferenceHelper.m
Sources/BranchSDK/BNCQRCodeCache.m
Sources/BranchSDK/BNCReachability.m
Sources/BranchSDK/BNCSKAdNetwork.m
Sources/BranchSDK/BNCServerAPI.m
Sources/BranchSDK/BNCServerRequestQueue.m
Sources/BranchSDK/BNCUserAgentCollector.m
Sources/BranchSDK/BranchContentDiscoverer.m
Sources/BranchSDK/BranchContentDiscoveryManifest.m
Sources/BranchSDK/BranchJsonConfig.m
Sources/BranchSDK/BranchLogger.m
Sources/BranchSDK/BranchPluginSupport.m
Sources/BranchSDK/BranchScene.m
Sources/BranchSDK/NSError+Branch.m

SDK-2302
Update to modern singleton creation syntax
Code modernization
There should be no functional change

SDK 2302 update singleton creation to dispatch once

---

BranchSDK.xcodeproj/project.pbxproj

SDK-2408 --  Investigate loss of AdSupport for Spotify
https://branch.atlassian.net/browse/SDK-2408
Fixed script names in "Run Script" phase of targets static-xcframework and  static-xcframework-noidfa.
**IDFA Support**
Generate a static framework by running script. - 
/scripts/prep_static_xcframework.sh
This will generate a static framework with IDFA support.
Link this framework to a test app with ATTrackingmanager support ( https://help.branch.io/developers-hub/docs/ios-advanced-features#include-apples-attrackingmanager).
Build and Run App. Check logs if idfa is present in requests -
```
"hardware_id" : "XXXXXXXXXXXX",
"hardware_id_type" : "idfa",
```
**IDFA Excluded**
Generate a static framework by running script. - 
./scripts/prep_static_xcframework_noidfa.sh
This will generate a …

Static Framework Missing IDFA Fix 

---

Sources/BranchSDK/Branch.m

INTENG-20410 - [Multiple] Purchase event being triggered twice in iOS
https://branch.atlassian.net/browse/INTENG-20410
In Event queue, `dequeue` function is replaced with `- (void)remove:(BNCServerRequest *)request` function. 
This fix will, instead of removing first event in the queue, will remove current event from the queue.
When In-App-Purchase sheet or Apple Pay sheet appears branch goes to inactive state. After payment is done, `logEvent` API is called inside the Apple/Stripe payment API callback. And then sheet is closed and app comes back to active state again. This creates two events -
* Standard Purchase Event
* Open Event
Following is order of events happened inside SDK:
* Standard Purchase Event Inserted in Queue and processing of Next Event in Queue is triggered by calling …

Double Purchase Event with ApplePay Fix

---

Sources/BranchSDK/BNCServerInterface.m
Sources/BranchSDK/BNCURLFilter.m
Sources/BranchSDK/BranchQRCode.m
Sources/BranchSDK/NSError+Branch.m
Sources/BranchSDK/Private/NSError+Branch.h

SDK-2470 -- Create new method for detecting VPN Ad blocker
Added `branchVPNBlockingError` to detect when a device is connected to a VPN and requests are failing with a specific error code.
Error Code Docs: https://developer.apple.com/documentation/cfnetwork/cfnetworkerrors/kcfurlerrorcannotconnecttohost?language=objc
CFNetworkingCopySystemProxySettings Docs:
https://developer.apple.com/documentation/cfnetwork/cfnetworkcopysystemproxysettings()
We want to provide more information in error logs to help clients with debugging regarding Branch.
Enable a VPN Ad Blocker and observe if requests are failing and returning the proper error logs.

[SDK-2470] Created branchVPNBlockingError method

---

Sources/BranchSDK/Branch.m
Sources/BranchSDK/Public/Branch.h

No JIRA ticket, based on Slack discussions
The `setRequestMetadataKey` function used to accept any object in the value parameter. The function is now modified to take in only a string or nil as Branch APIs cannot process non-string values for metadata.
The SDK exposes the `setRequestMetadataKey` function to allow developers to send in any value that can be attached with all event metadata. This includes IDs, custom parameters etc. 
As of today, the function takes in a string key with any value (string/bool/object/integer) without any errors. However, on passing a non-string value for metadata, one can observe that all Branch APIs start failing with a 400 error, citing invalid JSON. This is because the Branch APIs are designed to take in only string values for metadata. This can lead to …

fix: update metadata type to string

---

Sources/BranchSDK/BNCServerInterface.m
Sources/BranchSDK/BNCURLFilter.m
Sources/BranchSDK/BranchQRCode.m
Sources/BranchSDK/NSError+Branch.m
Sources/BranchSDK/Private/NSError+Branch.h

Updated the "Possible VPN/DNS Ad Blocker" logs from warnings to errors by changing the `BranchLogger` method used form `logWarning` to `logError`.
So clients can better identify these logs.
Use an ad blocker and confirm the logs appear as error logs instead of warnings now.

Updated ad blocker log warnings to errors

---

Sources/BranchSDK/BNCServerInterface.m
Sources/BranchSDK/BNCServerRequestQueue.m
Sources/BranchSDK/Branch.m
Sources/BranchSDK/BranchLogger.m
Sources/BranchSDK/BranchOpenRequest.m
Sources/BranchSDK/Private/BranchOpenRequest.h
Sources/BranchSDK/Public/BNCServerRequestQueue.h

Fix for Universal Link Cold Launch
Issues -
--   If tracking is disabled and app launch is cold, Universal Links were not resolving intermittently because of race condition happening between `branch.initSession` and `[BranchScene scene:continueUserActivity:]` for accessing preference variables. It happens only if both functions are called at the very same time. 
Following is the sequence of events which happens 
1. Session initialization starts from function `DidFinishLaunching` using `branch.initSession`. It has no `universal_link` in request. First Open Request is sent to server.
2. In the meantime  - `[BranchScene scene:continueUserActivity:]` is called and it has `universal_link` url . It sets this value in prefs. So when First open request is going out - it checks if its a linking …

Universal ink cold launch fix

---

Sources/BranchSDK/BNCRequestFactory.m
Sources/BranchSDK/Branch.m

SDK-2474 -- Fix for sending URI schemes as universal_link_urls
When the app was opened via URI scheme, the SDK was incorrectly setting the `universal_link_url` as that URI. This is because the URI would be passed into the request factory and there wasn't a check for if it was actually a universal link instead of a URI. This would lead to requests incorrectly having `external_intent_uri` and `universal_link_url` be the same value.
This change adds a check for if `urlString` contains http or https to confirm its a universal link.
To avoid having `universal_link_url` wrongly set to a URI.
Open your app via a uri scheme (e.g. branchtest://) before and after the change and observe the `external_intent_uri` and `universal_link_url` fields in the requests to make sure they look correct.
cc …

[SDK-2474] Fix for sending URI scheme as universal_link_url

---

Sources/BranchSDK/BNCRequestFactory.m
Sources/BranchSDK/Branch.m

SDK-2475 -- Fix bug where URL filter regex is being sent as external_intent_uri
We have been seeing requests where the external_intent_uri is one of the values in our URL filter pattern likes, like `"^fb\\d+:((?!campaign_ids).)*$"`. This appears to be due to a typo in the `handleDeepLink` function where if the link which opened the app matches the pattern, we set it as the `externalIntentURI` and `referringURL`. Changing this to set these fields to the actual URI seems to fix this issue and sends the proper requests.
**Branch.m**
```
pattern = [self.urlFilter patternMatchingURL:url];
if (!pattern) {
pattern = [self.userURLFilter patternMatchingURL:url];
}
if (pattern) {
self.preferenceHelper.dropURLOpen = YES;
//Problematic Lines
self.preferenceHelper.externalIntentURI = pattern; …
```

[SDK-2475] Fix for BNCURLFilter's regex being set as external_intent_uri

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
ChangeLog.md
DeepLinkDemo/DeepLinkDemo/Controllers/HomeViewController.swift
Sources/BranchSDK/BNCConfig.m
Sources/BranchSDK/Branch.m
scripts/version.sh

https://branch.atlassian.net/browse/INTENG-21106  - Double Opens Issue
iOS SDK sends two OPEN requests on cold launch (since Release 3.3 + ) if app is opened by clicking universal link.
First `OPEN` is sent by API `Branch.getInstance().initSessionWithLaunchOptions` and second `OPEN` is from  `Branch.getInstance().continue(userActivity)`
So if app sets a callback while initializing session using API `initSessionWithLaunchOptions`, this callback will be called twice on cold launch via universal link click.
This behavior came as a side effect to fix -  https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/pull/1369/files/2009c84ae1b603d963a5e064c2f5eb7e97f6f242. 
This pull request adds back some of the checks removed in above pull requests as well as adds few more.
As per the …

INTENG-21106 Fix for double opens

---

Branch-TestBed/Branch-SDK-Tests/BNCServerRequestQueueTests.m
BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
ChangeLog.md
Sources/BranchSDK/BNCConfig.m
Sources/BranchSDK/BNCServerRequestQueue.m
scripts/version.sh

https://branch.atlassian.net/browse/INTENG-21262 
Issue : SDK sends Duplicate purchase events on cold launch of app if network request processing failed in previous launches.
SDK archives a copy of its Request Queue on Disk. Its a txt file (`BNCServerRequestQueue`)stored inside the `Application Support` folder of the data container of app. This archived copy is updated at regular intervals using a timer. 
When app is cold launched, SDK reads this file and adds requests left unprocessed from last run in its Request Queue. 
Because of a bug in SDK, this archived file was not deleted from disk if current request queue is empty. As a result, SDK keeps sending these cached requests on every cold launch of app.
Steps for reproducing bug :
1. Turn off WIFI / internet
2. Send any Standard or …

[IN PROGRESS] INTENG-21262 Fix for Duplicate purchase events (cached).

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
ChangeLog.md
Sources/BranchSDK/BNCConfig.m
scripts/version.sh

- Added `setConsumerProtectionAttributionLevel` for controlling attribution data collection
- Deprecated `setTrackingDisabled` in favor of `setConsumerProtectionAttributionLevel(NONE)`

Release 3.7.0

---

Branch-TestBed/Branch-TestBed/AppDelegate.m
Sources/BranchSDK/BNCServerInterface.m
Sources/BranchSDK/Branch.m
Sources/BranchSDK/BranchLogger.m
Sources/BranchSDK/Public/Branch.h
Sources/BranchSDK/Public/BranchLogger.h

SDK-2427 -- Add request & response objects to the BranchLogCallback
Updates the BranchLogCallback to include the request and response objects themselves rather than just include the data in the log message.
Make it easier to parse networking logs.
Try out the new BranchLogCallback with the request and response. This is a breaking change since it adds new fields to the BranchLogCallback

[SDK-2527] Add request & response objects to the BranchLogCallback

---

Sources/BranchSDK/Branch.m
Sources/BranchSDK/BranchJsonConfig.m
Sources/BranchSDK/Private/BranchJsonConfig.h

SDK-2522 -- Support CPP Level in Branch.json
Added a check in the brach.json for the CPP Level
To support setting it early and in plugins easily.
Add `consumerProtectionAttributionLevel: "Full/Reduced/None"` to branch.json and observe the CPP level being changed.

[SDK-2522] Set CPP Level via branch.json

---

Framework/BranchSDK.h
Sources/BranchSDK/Public/BranchSDK.h

INTENG-21518
Removed a check for tvOS when including certain files in the umbrella header. Since the files themselves contain the tvOS checks, this one appears to be unnecessary and caused Xcode to be unable to locate these files when building an app with the SDK.
Fix for clients using tvOS apps.
Compile and run the app to make sure it still builds on different integrations as well.

[INTENG-21518] Fix for compilation issue on tvOS

---

Branch-TestBed/Branch-TestBed/AppDelegate.m
Sources/BranchSDK/Branch.m

When a BranchEvent is logged on first open before the SDK is initialized, we try to initialize first to log it properly. However, the SDK was reaching a state where `processNextQueueItem` was stuck and unable to process the first install or the event and nothing would happen until the next session. It seems like this was due to the BranchEvent request basically causing the queue to get stuck and the SDK to stay in an initializing state since `processNextQueueItem` would be skipped `networkCount` wasn't equal to 0. 
This change updates the if statement to also set the networkCount to 0 which allows the install to be processed and then the event to be processed after that. Since this statement only applies to non-install or open events on the first session, this change shouldn't have an …

[SDK-2473] Fix for early branch init on install

---

Branch-TestBed/Branch-SDK-Tests/BNCServerInterfaceTests.m
Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj
Sources/BranchSDK/BNCServerInterface.m
Sources/BranchSDK/Branch.m

SDK-2530 -- Fix Init Race for Push notifications
https://branch.atlassian.net/browse/SDK-2530
SDK-2532 -- If tracking is disabled and app is launched via spotlight results, linking request is not sent.
https://branch.atlassian.net/browse/SDK-2532
Fixes :
* Push notifications are handled via `handlePushNotification` API which is called inside didReceiveRemoteNotification. So `initSessionWithLaunchOptions` is updated to not to send and extra open and call callback if app is launched via push notification.
* Fixed isLinkingRelatedRequest function to allow opens if tracking is disabled and spotlight identifier is present.
* Launch App via push notification and verify  initsession callback is called only once ( cold launch app, warm launch + active app , warm launch + background app )
* …

Misc Bug Fixes : SDK-2530, SDK-2532

---

Sources/BranchSDK/Branch.m
Sources/BranchSDK/Public/Branch.h

SDK-2537 -- Fix enableLogging API error - Ambiguous use of 'enableLogging'
https://branch.atlassian.net/browse/SDK-2537
Following are two overloaded versions of static API `enableLoggingAtLevel` and both had the second param `nullable` attribute. This resulted in two methods with same name and same param.
```
+ (void)enableLoggingAtLevel:(BranchLogLevel)logLevel withCallback:(nullable BranchLogCallback)callback;
+ (void)enableLoggingAtLevel:(BranchLogLevel)logLevel withAdvancedCallback:(nullable  BranchAdvancedLogCallback)callback;
```
In a test app, call API ` Branch.enableLogging(at: .verbose)`. Compile app to see we no longer get Build error.

Removed 'nullable' attribute of BranchAdvancedLogCallback param

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
ChangeLog.md
Sources/BranchSDK/BNCConfig.m
scripts/version.sh

Version and Change Log Updates.

Release 3.9

---

.github/workflows/verify.yml
BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
Framework/BranchSDK.h
Sources/BranchSDK/Public/BranchSDK.h

INTENG-21518 : tvOS v3.5.1 and v3.6.4 are throwing compilation errors addressed in previous INTENG due to clients updated implementation
https://branch.atlassian.net/browse/INTENG-21518
Branch SDK umbrella header file is common for all the platforms. Some files are for iOS platform only. Branch SDK handles platform specific code using preprocessor checks.  Module map and SPM manifest file has also configuration common for all the platforms. This works fine if app is iOS only or tvOS only. But it fails for a hybrid app.
This PR includes following workarounds :
SPM :  Removed a check for tvOS when including certain files in the umbrella header. Since the files themselves contain the tvOS checks, this one appears to be unnecessary and caused Xcode to be unable to locate these files when …

INTENG-21518 - SPM + Hybrid app compilation issue.

---

Sources/BranchSDK/BranchOpenRequest.m

[INTENG-22230] 
To be consistent, nil out initial referrer as we do for other fields after an open request succeeds. Otherwise, it is not guaranteed that storage would be cleared out and previous initial referrer value could be reused. 
[INTENG-22230]: https://branch.atlassian.net/browse/INTENG-22230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[INTENG-22230] Clear initial referrer after init

---

Branch-TestBed/Branch-SDK-Tests/BNCAPIServerTest.m
Sources/BranchSDK/BNCServerAPI.m
Sources/BranchSDK/Branch.m
Sources/BranchSDK/Private/BNCServerAPI.h
Sources/BranchSDK/Public/Branch.h

EMT-1779 -- [iOS SDK] Provide setSafetrackAPIURL utility to override BNC_SAFETRACK_API_URL
https://branch.atlassian.net/browse/EMT-1779
Added new API - `setSafetrackAPIURL`. It overrides `BNC_SAFETRACK_API_URL`. 
If app sets a custom safe track url and user opts in for IDFA collection (useTrackingDomain is true), this custom url will be used for all v2 requests, v1/open and v1/install.
* Verify all unit tests pass ( This PR adds two new tests - testSetSafeTrackServiceURLWithUserTrackingDomain and testSetSafeTrackServiceURLWithOutUserTrackingDomain)
* Set a custom safetrack url using this new API - setSafetrackAPIURL in any test. Opt in for IDFA collection or manually set following params 
`BNCServerAPI *serverAPI = [BNCServerAPI sharedInstance];
serverAPI.automaticallyEnableTrackingDomain …

Added  API setSafetrackAPIURL

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
ChangeLog.md
Sources/BranchSDK/BNCConfig.m
scripts/version.sh

EMT-1684 - ODM - On Device Measurement
https://branch.atlassian.net/browse/EMT-1684
Version and Change Log Updates.

Release 3.11.0 Updates

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
ChangeLog.md
Sources/BranchSDK/BNCConfig.m
scripts/version.sh

Release 3.12.0 Version and Change Log Updates

Release 3.12.0 Updates.

---

Branch-TestBed/Branch-SDK-Tests/BNCReferringURLUtilityTests.m
Sources/BranchSDK/BNCReferringURLUtility.m

INTENG-22710 -- https://branch.atlassian.net/browse/INTENG-22710
Opening Facebook generated URI scheme crashes iOS SDK
This PR fixes above crash. It includes -
-> Checks to ensure data type of the object returned from the `[NSJSONSerialization JSONObjectWithData:jsonData options:0 error:&error] ` is a dictionary.
-> Added nil check for URL
-> Added unit tests
Fix crash when Facebook generated URI does not contain campaign IDs.
Please refer to INTENG-22710 to get the URI on which Apps are crashing.
Apps should not crash when URI mentioned in JIRA ticket  is clicked.

Added checks for empty url and class type. Added unit tests also.

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
ChangeLog.md
Sources/BranchSDK/BNCConfig.m
scripts/version.sh

Release 3.12.1 Version and ChangeLog Updates.

---

.github/workflows/release.yml
scripts/build_xcframework.sh
scripts/build_xcframework_noidfa.sh
scripts/prep_xcframework.sh
scripts/prep_xcframework_noidfa.sh

EMT-1964 - Automate Code Signing and Debug Symbol Generation for iOS SDK Released Binaries
https://branch.atlassian.net/browse/EMT-1964
This PR has updated build scripts and updated GHA  for release process to generate signed binaries and binaries with dSym
Not yet tested as this will create a new release in Github page and this action will run only after its merged into master.

Emt 1964 Automate code signing and dSym binaries generation

---

Sources/BranchSDK/BNCServerInterface.m

Create NSError object when error object is returned from services

---

BranchSDK.podspec
BranchSDK.xcodeproj/project.pbxproj
ChangeLog.md
Sources/BranchSDK/BNCConfig.m
scripts/version.sh

Release 3.13.0 Version and ChangeLog Updates

Release 3.13.0 Updates.

---

Sources/BranchSDK/Branch.m

EMT-2424 - https://branch.atlassian.net/browse/EMT-2424 

Retry logic updated for Http Response Codes 1xx, 2xx, 3xx and 4xx.

---

SDKIntegrationTestApps/iOSReleaseTest-SPM/iOSReleaseTest.xcodeproj/project.pbxproj
Sources/BranchSDK/Public/BranchEvent.h

EMT-2434 - StoreKit APIs Deprecation
https://branch.atlassian.net/browse/EMT-2434

Disabled Deprecation warning for StoreKit(Original) APIs

---

Branch-TestBed/Branch-TestBed/AppDelegate.m
Sources/BranchSDK/BNCODMInfoCollector.m
Sources/BranchSDK/Branch.m
Sources/BranchSDK/BranchInstallRequest.m
Sources/BranchSDK/BranchOpenRequest.m
Sources/BranchSDK/Private/BranchOpenRequest.h
Sources/BranchSDK/Public/BNCCallbacks.h
Sources/BranchSDK/Public/Branch.h

Custom callback test
